// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &bleConfigResource{}
	_ resource.ResourceWithImportState = &bleConfigResource{}
)

func NewBLEConfigResource() resource.Resource { return &bleConfigResource{} }

type bleConfigResource struct{}

type bleConfigRPCModel struct {
	Enable types.Bool `tfsdk:"enable"`
}

type bleConfigResourceModel struct {
	IP  types.String `tfsdk:"ip"`
	RPC types.Object `tfsdk:"rpc"`
}

var bleConfigRPCAttrTypes = map[string]attr.Type{
	"enable": types.BoolType,
}

func (r *bleConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ble_config"
}

func (r *bleConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"rpc": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "True if rpc service is enabled, false otherwise",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
				},
			},
		},
	}
}

func (r *bleConfigResource) get(ctx context.Context, m *bleConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.BLEGetConfigRequest{}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.RPC != nil {
		var sRPC bleConfigRPCModel
		if !m.RPC.IsNull() && !m.RPC.IsUnknown() {
			diags.Append(m.RPC.As(ctx, &sRPC, basetypes.ObjectAsOptions{})...)
		}
		if got.RPC.Enable != nil {
			sRPC.Enable = types.BoolValue(*got.RPC.Enable)
		} else if sRPC.Enable.IsUnknown() {
			sRPC.Enable = types.BoolNull()
		}
		oRPC, dRPC := types.ObjectValueFrom(ctx, bleConfigRPCAttrTypes, sRPC)
		diags.Append(dRPC...)
		m.RPC = oRPC
	} else {
		m.RPC = types.ObjectNull(bleConfigRPCAttrTypes)
	}
}

func (r *bleConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state bleConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *bleConfigResource) apply(ctx context.Context, plan bleConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.BLEConfig
	if !plan.RPC.IsNull() && !plan.RPC.IsUnknown() {
		var wRPC bleConfigRPCModel
		diags.Append(plan.RPC.As(ctx, &wRPC, basetypes.ObjectAsOptions{})...)
		cfg.RPC = &components.BLEConfigRPC{}
		if !wRPC.Enable.IsNull() && !wRPC.Enable.IsUnknown() {
			v := wRPC.Enable.ValueBool()
			cfg.RPC.Enable = &v
		}
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.BLESetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *bleConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan bleConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *bleConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan bleConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *bleConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *bleConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
