// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/float64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &coverConfigResource{}
	_ resource.ResourceWithImportState = &coverConfigResource{}
)

func NewCoverConfigResource() resource.Resource { return &coverConfigResource{} }

type coverConfigResource struct{}

type coverConfigMotorModel struct {
	IdlePowerThr      types.Float64 `tfsdk:"idle_power_thr"`
	IdleConfirmPeriod types.Float64 `tfsdk:"idle_confirm_period"`
}

type coverConfigObstructionDetectionModel struct {
	Enable    types.Bool    `tfsdk:"enable"`
	Direction types.String  `tfsdk:"direction"`
	Action    types.String  `tfsdk:"action"`
	PowerThr  types.Float64 `tfsdk:"power_thr"`
	Holdoff   types.Float64 `tfsdk:"holdoff"`
}

type coverConfigSafetySwitchModel struct {
	Enable      types.Bool   `tfsdk:"enable"`
	Direction   types.String `tfsdk:"direction"`
	Action      types.String `tfsdk:"action"`
	AllowedMove types.String `tfsdk:"allowed_move"`
}

type coverConfigSlatModel struct {
	Enable     types.Bool    `tfsdk:"enable"`
	OpenTime   types.Float64 `tfsdk:"open_time"`
	CloseTime  types.Float64 `tfsdk:"close_time"`
	Step       types.Float64 `tfsdk:"step"`
	RetainPos  types.Bool    `tfsdk:"retain_pos"`
	PreciseCtl types.Bool    `tfsdk:"precise_ctl"`
}

type coverConfigResourceModel struct {
	IP                   types.String  `tfsdk:"ip"`
	ID                   types.Int64   `tfsdk:"id"`
	Name                 types.String  `tfsdk:"name"`
	InMode               types.String  `tfsdk:"in_mode"`
	InLocked             types.Bool    `tfsdk:"in_locked"`
	InitialState         types.String  `tfsdk:"initial_state"`
	PowerLimit           types.Float64 `tfsdk:"power_limit"`
	VoltageLimit         types.Float64 `tfsdk:"voltage_limit"`
	UndervoltageLimit    types.Float64 `tfsdk:"undervoltage_limit"`
	CurrentLimit         types.Float64 `tfsdk:"current_limit"`
	Motor                types.Object  `tfsdk:"motor"`
	MaxtimeOpen          types.Float64 `tfsdk:"maxtime_open"`
	MaxtimeClose         types.Float64 `tfsdk:"maxtime_close"`
	InvertDirections     types.Bool    `tfsdk:"invert_directions"`
	MaintenanceMode      types.Bool    `tfsdk:"maintenance_mode"`
	ObstructionDetection types.Object  `tfsdk:"obstruction_detection"`
	SafetySwitch         types.Object  `tfsdk:"safety_switch"`
	Slat                 types.Object  `tfsdk:"slat"`
	SwapInputs           types.Bool    `tfsdk:"swap_inputs"`
}

var coverConfigMotorAttrTypes = map[string]attr.Type{
	"idle_power_thr":      types.Float64Type,
	"idle_confirm_period": types.Float64Type,
}

var coverConfigObstructionDetectionAttrTypes = map[string]attr.Type{
	"enable":    types.BoolType,
	"direction": types.StringType,
	"action":    types.StringType,
	"power_thr": types.Float64Type,
	"holdoff":   types.Float64Type,
}

var coverConfigSafetySwitchAttrTypes = map[string]attr.Type{
	"enable":       types.BoolType,
	"direction":    types.StringType,
	"action":       types.StringType,
	"allowed_move": types.StringType,
}

var coverConfigSlatAttrTypes = map[string]attr.Type{
	"enable":      types.BoolType,
	"open_time":   types.Float64Type,
	"close_time":  types.Float64Type,
	"step":        types.Float64Type,
	"retain_pos":  types.BoolType,
	"precise_ctl": types.BoolType,
}

func (r *coverConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cover_config"
}

func (r *coverConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the Cover component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the Cover component instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"in_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "One of single, dual or detached, only present if there is at least one input associated with the Cover instance: single, dual, detached.",
				Validators:          []validator.String{stringvalidator.OneOf("single", "dual", "detached")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"in_locked": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "If True, all changes to physical inputs are ignored, regardless of mode.",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"initial_state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Defines Cover target state on power-on, one of open (Cover will fully open), closed (Cover will fully close) or stopped (Cover will not change its position)",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"power_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Watts, a limit that must be exceeded to trigger an overpower error",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"voltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Volts, a limit that must be exceeded to trigger an overvoltage error",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"undervoltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Volts, a limit that must be subceeded to trigger an undervoltage error",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"current_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Amperes, a limit that must be exceeded to trigger an overcurrent error",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"motor": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"idle_power_thr": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Watts, threshold below which the motor is considered stopped",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"idle_confirm_period": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Seconds, the minimum period of time in idle state before the state is confirmed",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
			"maxtime_open": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Default timeout after which Cover will stop moving in open direction",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"maxtime_close": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Default timeout after which Cover will stop moving in a close direction",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"invert_directions": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Defines the motor rotation for open and close directions (changing this parameter requires a reboot): false, true.",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"maintenance_mode": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Can be used to temporarily freeze all motions for maintenance: false, true.",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"obstruction_detection": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "true when obstruction detection is enabled, false otherwise",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"direction": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "The direction of motion for which the safety switch should be monitored, one of open, close, both",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"action": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "The recovery action that should be performed if the safety switch is engaged while moving in a monitored direction, one of the: stop, reverse.",
						Validators:          []validator.String{stringvalidator.OneOf("stop", "reverse")},
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"power_thr": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Watts, power consumption above this threshold should be interpreted as objects obstructing Cover movement. This property is editable at any time, but note that during the cover calibration procedure (Cover.Calibrate), power_thr will be automatically set to the peak power consumption + 15%, overwriting the current value. The automatic setup of power_thr during calibration will only start tracking power values when the holdoff time (see below) has elapsed",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"holdoff": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Seconds, time to wait after Cover starts moving before obstruction detection is activated (to avoid false detections because of the initial power consumption spike)",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
			"safety_switch": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "true when the safety switch is enabled, false otherwise",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"direction": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "The direction of motion for which the safety switch should be monitored, one of open, close, both",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"action": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "The recovery action which should be performed if the safety switch is engaged while moving in a monitored direction, is one of the: stop, reverse, pause.",
						Validators:          []validator.String{stringvalidator.OneOf("stop", "reverse", "pause")},
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"allowed_move": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Allowed movement direction when the safety switch is engaged while moving in a monitored direction: null, reverse.",
						Validators:          []validator.String{stringvalidator.OneOf("reverse")},
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
				},
			},
			"slat": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "true when slat control is enabled, false otherwise",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"open_time": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Time it takes for slats to move from fully closed (0%) to fully open (100%) position, seconds. Must be manually configured by the user. Accepted range: [0.5..30]s",
						Validators:          []validator.Float64{float64validator.Between(0.5, 30)},
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"close_time": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Time it takes for slats to move from fully open (100%) to fully closed (100%) position, seconds. Must be manually configured by the user. Accepted range: [0.5..30]s",
						Validators:          []validator.Float64{float64validator.Between(0.5, 30)},
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"step": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Single step movement spread, represented as % from the full range (used only when slats are controlled via inputs). Accepted range: [1..100]%",
						Validators:          []validator.Float64{float64validator.Between(1, 100)},
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"retain_pos": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Whether to retain slat position when cover (vertical) position is changed",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"precise_ctl": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "This property only applies when cover (vertical) position is less than one full slat rotation away from the fully closed position. If this condition is met, any slat movement will always go through fully closed position first. This improves slat positioning accuracy, yet is slower to execute.",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
				},
			},
			"swap_inputs": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Defines whether the functions of the two inputs are swapped. Only present if there are two inputs associated with the Cover instance.",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *coverConfigResource) get(ctx context.Context, m *coverConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.CoverGetConfigRequest{ID: int(m.ID.ValueInt64())}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		m.Name = types.StringValue(*got.Name)
	} else if m.Name.IsUnknown() {
		m.Name = types.StringNull()
	}
	if got.InMode != nil {
		m.InMode = types.StringValue(*got.InMode)
	} else if m.InMode.IsUnknown() {
		m.InMode = types.StringNull()
	}
	if got.InLocked != nil {
		m.InLocked = types.BoolValue(*got.InLocked)
	} else if m.InLocked.IsUnknown() {
		m.InLocked = types.BoolNull()
	}
	if got.InitialState != nil {
		m.InitialState = types.StringValue(*got.InitialState)
	} else if m.InitialState.IsUnknown() {
		m.InitialState = types.StringNull()
	}
	if got.PowerLimit != nil {
		m.PowerLimit = types.Float64Value(*got.PowerLimit)
	} else if m.PowerLimit.IsUnknown() {
		m.PowerLimit = types.Float64Null()
	}
	if got.VoltageLimit != nil {
		m.VoltageLimit = types.Float64Value(*got.VoltageLimit)
	} else if m.VoltageLimit.IsUnknown() {
		m.VoltageLimit = types.Float64Null()
	}
	if got.UndervoltageLimit != nil {
		m.UndervoltageLimit = types.Float64Value(*got.UndervoltageLimit)
	} else if m.UndervoltageLimit.IsUnknown() {
		m.UndervoltageLimit = types.Float64Null()
	}
	if got.CurrentLimit != nil {
		m.CurrentLimit = types.Float64Value(*got.CurrentLimit)
	} else if m.CurrentLimit.IsUnknown() {
		m.CurrentLimit = types.Float64Null()
	}
	if got.Motor != nil {
		var sMotor coverConfigMotorModel
		if !m.Motor.IsNull() && !m.Motor.IsUnknown() {
			diags.Append(m.Motor.As(ctx, &sMotor, basetypes.ObjectAsOptions{})...)
		}
		if got.Motor.IdlePowerThr != nil {
			sMotor.IdlePowerThr = types.Float64Value(*got.Motor.IdlePowerThr)
		} else if sMotor.IdlePowerThr.IsUnknown() {
			sMotor.IdlePowerThr = types.Float64Null()
		}
		if got.Motor.IdleConfirmPeriod != nil {
			sMotor.IdleConfirmPeriod = types.Float64Value(*got.Motor.IdleConfirmPeriod)
		} else if sMotor.IdleConfirmPeriod.IsUnknown() {
			sMotor.IdleConfirmPeriod = types.Float64Null()
		}
		oMotor, dMotor := types.ObjectValueFrom(ctx, coverConfigMotorAttrTypes, sMotor)
		diags.Append(dMotor...)
		m.Motor = oMotor
	} else {
		m.Motor = types.ObjectNull(coverConfigMotorAttrTypes)
	}
	if got.MaxtimeOpen != nil {
		m.MaxtimeOpen = types.Float64Value(*got.MaxtimeOpen)
	} else if m.MaxtimeOpen.IsUnknown() {
		m.MaxtimeOpen = types.Float64Null()
	}
	if got.MaxtimeClose != nil {
		m.MaxtimeClose = types.Float64Value(*got.MaxtimeClose)
	} else if m.MaxtimeClose.IsUnknown() {
		m.MaxtimeClose = types.Float64Null()
	}
	if got.InvertDirections != nil {
		m.InvertDirections = types.BoolValue(*got.InvertDirections)
	} else if m.InvertDirections.IsUnknown() {
		m.InvertDirections = types.BoolNull()
	}
	if got.MaintenanceMode != nil {
		m.MaintenanceMode = types.BoolValue(*got.MaintenanceMode)
	} else if m.MaintenanceMode.IsUnknown() {
		m.MaintenanceMode = types.BoolNull()
	}
	if got.ObstructionDetection != nil {
		var sObstructionDetection coverConfigObstructionDetectionModel
		if !m.ObstructionDetection.IsNull() && !m.ObstructionDetection.IsUnknown() {
			diags.Append(m.ObstructionDetection.As(ctx, &sObstructionDetection, basetypes.ObjectAsOptions{})...)
		}
		if got.ObstructionDetection.Enable != nil {
			sObstructionDetection.Enable = types.BoolValue(*got.ObstructionDetection.Enable)
		} else if sObstructionDetection.Enable.IsUnknown() {
			sObstructionDetection.Enable = types.BoolNull()
		}
		if got.ObstructionDetection.Direction != nil {
			sObstructionDetection.Direction = types.StringValue(*got.ObstructionDetection.Direction)
		} else if sObstructionDetection.Direction.IsUnknown() {
			sObstructionDetection.Direction = types.StringNull()
		}
		if got.ObstructionDetection.Action != nil {
			sObstructionDetection.Action = types.StringValue(*got.ObstructionDetection.Action)
		} else if sObstructionDetection.Action.IsUnknown() {
			sObstructionDetection.Action = types.StringNull()
		}
		if got.ObstructionDetection.PowerThr != nil {
			sObstructionDetection.PowerThr = types.Float64Value(*got.ObstructionDetection.PowerThr)
		} else if sObstructionDetection.PowerThr.IsUnknown() {
			sObstructionDetection.PowerThr = types.Float64Null()
		}
		if got.ObstructionDetection.Holdoff != nil {
			sObstructionDetection.Holdoff = types.Float64Value(*got.ObstructionDetection.Holdoff)
		} else if sObstructionDetection.Holdoff.IsUnknown() {
			sObstructionDetection.Holdoff = types.Float64Null()
		}
		oObstructionDetection, dObstructionDetection := types.ObjectValueFrom(ctx, coverConfigObstructionDetectionAttrTypes, sObstructionDetection)
		diags.Append(dObstructionDetection...)
		m.ObstructionDetection = oObstructionDetection
	} else {
		m.ObstructionDetection = types.ObjectNull(coverConfigObstructionDetectionAttrTypes)
	}
	if got.SafetySwitch != nil {
		var sSafetySwitch coverConfigSafetySwitchModel
		if !m.SafetySwitch.IsNull() && !m.SafetySwitch.IsUnknown() {
			diags.Append(m.SafetySwitch.As(ctx, &sSafetySwitch, basetypes.ObjectAsOptions{})...)
		}
		if got.SafetySwitch.Enable != nil {
			sSafetySwitch.Enable = types.BoolValue(*got.SafetySwitch.Enable)
		} else if sSafetySwitch.Enable.IsUnknown() {
			sSafetySwitch.Enable = types.BoolNull()
		}
		if got.SafetySwitch.Direction != nil {
			sSafetySwitch.Direction = types.StringValue(*got.SafetySwitch.Direction)
		} else if sSafetySwitch.Direction.IsUnknown() {
			sSafetySwitch.Direction = types.StringNull()
		}
		if got.SafetySwitch.Action != nil {
			sSafetySwitch.Action = types.StringValue(*got.SafetySwitch.Action)
		} else if sSafetySwitch.Action.IsUnknown() {
			sSafetySwitch.Action = types.StringNull()
		}
		if got.SafetySwitch.AllowedMove != nil {
			sSafetySwitch.AllowedMove = types.StringValue(*got.SafetySwitch.AllowedMove)
		} else if sSafetySwitch.AllowedMove.IsUnknown() {
			sSafetySwitch.AllowedMove = types.StringNull()
		}
		oSafetySwitch, dSafetySwitch := types.ObjectValueFrom(ctx, coverConfigSafetySwitchAttrTypes, sSafetySwitch)
		diags.Append(dSafetySwitch...)
		m.SafetySwitch = oSafetySwitch
	} else {
		m.SafetySwitch = types.ObjectNull(coverConfigSafetySwitchAttrTypes)
	}
	if got.Slat != nil {
		var sSlat coverConfigSlatModel
		if !m.Slat.IsNull() && !m.Slat.IsUnknown() {
			diags.Append(m.Slat.As(ctx, &sSlat, basetypes.ObjectAsOptions{})...)
		}
		if got.Slat.Enable != nil {
			sSlat.Enable = types.BoolValue(*got.Slat.Enable)
		} else if sSlat.Enable.IsUnknown() {
			sSlat.Enable = types.BoolNull()
		}
		if got.Slat.OpenTime != nil {
			sSlat.OpenTime = types.Float64Value(*got.Slat.OpenTime)
		} else if sSlat.OpenTime.IsUnknown() {
			sSlat.OpenTime = types.Float64Null()
		}
		if got.Slat.CloseTime != nil {
			sSlat.CloseTime = types.Float64Value(*got.Slat.CloseTime)
		} else if sSlat.CloseTime.IsUnknown() {
			sSlat.CloseTime = types.Float64Null()
		}
		if got.Slat.Step != nil {
			sSlat.Step = types.Float64Value(*got.Slat.Step)
		} else if sSlat.Step.IsUnknown() {
			sSlat.Step = types.Float64Null()
		}
		if got.Slat.RetainPos != nil {
			sSlat.RetainPos = types.BoolValue(*got.Slat.RetainPos)
		} else if sSlat.RetainPos.IsUnknown() {
			sSlat.RetainPos = types.BoolNull()
		}
		if got.Slat.PreciseCtl != nil {
			sSlat.PreciseCtl = types.BoolValue(*got.Slat.PreciseCtl)
		} else if sSlat.PreciseCtl.IsUnknown() {
			sSlat.PreciseCtl = types.BoolNull()
		}
		oSlat, dSlat := types.ObjectValueFrom(ctx, coverConfigSlatAttrTypes, sSlat)
		diags.Append(dSlat...)
		m.Slat = oSlat
	} else {
		m.Slat = types.ObjectNull(coverConfigSlatAttrTypes)
	}
	if got.SwapInputs != nil {
		m.SwapInputs = types.BoolValue(*got.SwapInputs)
	} else if m.SwapInputs.IsUnknown() {
		m.SwapInputs = types.BoolNull()
	}
}

func (r *coverConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state coverConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *coverConfigResource) apply(ctx context.Context, plan coverConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.CoverConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.InMode.IsNull() && !plan.InMode.IsUnknown() {
		v := plan.InMode.ValueString()
		cfg.InMode = &v
	}
	if !plan.InLocked.IsNull() && !plan.InLocked.IsUnknown() {
		v := plan.InLocked.ValueBool()
		cfg.InLocked = &v
	}
	if !plan.InitialState.IsNull() && !plan.InitialState.IsUnknown() {
		v := plan.InitialState.ValueString()
		cfg.InitialState = &v
	}
	if !plan.PowerLimit.IsNull() && !plan.PowerLimit.IsUnknown() {
		v := plan.PowerLimit.ValueFloat64()
		cfg.PowerLimit = &v
	}
	if !plan.VoltageLimit.IsNull() && !plan.VoltageLimit.IsUnknown() {
		v := plan.VoltageLimit.ValueFloat64()
		cfg.VoltageLimit = &v
	}
	if !plan.UndervoltageLimit.IsNull() && !plan.UndervoltageLimit.IsUnknown() {
		v := plan.UndervoltageLimit.ValueFloat64()
		cfg.UndervoltageLimit = &v
	}
	if !plan.CurrentLimit.IsNull() && !plan.CurrentLimit.IsUnknown() {
		v := plan.CurrentLimit.ValueFloat64()
		cfg.CurrentLimit = &v
	}
	if !plan.Motor.IsNull() && !plan.Motor.IsUnknown() {
		var wMotor coverConfigMotorModel
		diags.Append(plan.Motor.As(ctx, &wMotor, basetypes.ObjectAsOptions{})...)
		cfg.Motor = &components.CoverConfigMotor{}
		if !wMotor.IdlePowerThr.IsNull() && !wMotor.IdlePowerThr.IsUnknown() {
			v := wMotor.IdlePowerThr.ValueFloat64()
			cfg.Motor.IdlePowerThr = &v
		}
		if !wMotor.IdleConfirmPeriod.IsNull() && !wMotor.IdleConfirmPeriod.IsUnknown() {
			v := wMotor.IdleConfirmPeriod.ValueFloat64()
			cfg.Motor.IdleConfirmPeriod = &v
		}
	}
	if !plan.MaxtimeOpen.IsNull() && !plan.MaxtimeOpen.IsUnknown() {
		v := plan.MaxtimeOpen.ValueFloat64()
		cfg.MaxtimeOpen = &v
	}
	if !plan.MaxtimeClose.IsNull() && !plan.MaxtimeClose.IsUnknown() {
		v := plan.MaxtimeClose.ValueFloat64()
		cfg.MaxtimeClose = &v
	}
	if !plan.InvertDirections.IsNull() && !plan.InvertDirections.IsUnknown() {
		v := plan.InvertDirections.ValueBool()
		cfg.InvertDirections = &v
	}
	if !plan.MaintenanceMode.IsNull() && !plan.MaintenanceMode.IsUnknown() {
		v := plan.MaintenanceMode.ValueBool()
		cfg.MaintenanceMode = &v
	}
	if !plan.ObstructionDetection.IsNull() && !plan.ObstructionDetection.IsUnknown() {
		var wObstructionDetection coverConfigObstructionDetectionModel
		diags.Append(plan.ObstructionDetection.As(ctx, &wObstructionDetection, basetypes.ObjectAsOptions{})...)
		cfg.ObstructionDetection = &components.CoverConfigObstructionDetection{}
		if !wObstructionDetection.Enable.IsNull() && !wObstructionDetection.Enable.IsUnknown() {
			v := wObstructionDetection.Enable.ValueBool()
			cfg.ObstructionDetection.Enable = &v
		}
		if !wObstructionDetection.Direction.IsNull() && !wObstructionDetection.Direction.IsUnknown() {
			v := wObstructionDetection.Direction.ValueString()
			cfg.ObstructionDetection.Direction = &v
		}
		if !wObstructionDetection.Action.IsNull() && !wObstructionDetection.Action.IsUnknown() {
			v := wObstructionDetection.Action.ValueString()
			cfg.ObstructionDetection.Action = &v
		}
		if !wObstructionDetection.PowerThr.IsNull() && !wObstructionDetection.PowerThr.IsUnknown() {
			v := wObstructionDetection.PowerThr.ValueFloat64()
			cfg.ObstructionDetection.PowerThr = &v
		}
		if !wObstructionDetection.Holdoff.IsNull() && !wObstructionDetection.Holdoff.IsUnknown() {
			v := wObstructionDetection.Holdoff.ValueFloat64()
			cfg.ObstructionDetection.Holdoff = &v
		}
	}
	if !plan.SafetySwitch.IsNull() && !plan.SafetySwitch.IsUnknown() {
		var wSafetySwitch coverConfigSafetySwitchModel
		diags.Append(plan.SafetySwitch.As(ctx, &wSafetySwitch, basetypes.ObjectAsOptions{})...)
		cfg.SafetySwitch = &components.CoverConfigSafetySwitch{}
		if !wSafetySwitch.Enable.IsNull() && !wSafetySwitch.Enable.IsUnknown() {
			v := wSafetySwitch.Enable.ValueBool()
			cfg.SafetySwitch.Enable = &v
		}
		if !wSafetySwitch.Direction.IsNull() && !wSafetySwitch.Direction.IsUnknown() {
			v := wSafetySwitch.Direction.ValueString()
			cfg.SafetySwitch.Direction = &v
		}
		if !wSafetySwitch.Action.IsNull() && !wSafetySwitch.Action.IsUnknown() {
			v := wSafetySwitch.Action.ValueString()
			cfg.SafetySwitch.Action = &v
		}
		if !wSafetySwitch.AllowedMove.IsNull() && !wSafetySwitch.AllowedMove.IsUnknown() {
			v := wSafetySwitch.AllowedMove.ValueString()
			cfg.SafetySwitch.AllowedMove = &v
		}
	}
	if !plan.Slat.IsNull() && !plan.Slat.IsUnknown() {
		var wSlat coverConfigSlatModel
		diags.Append(plan.Slat.As(ctx, &wSlat, basetypes.ObjectAsOptions{})...)
		cfg.Slat = &components.CoverConfigSlat{}
		if !wSlat.Enable.IsNull() && !wSlat.Enable.IsUnknown() {
			v := wSlat.Enable.ValueBool()
			cfg.Slat.Enable = &v
		}
		if !wSlat.OpenTime.IsNull() && !wSlat.OpenTime.IsUnknown() {
			v := wSlat.OpenTime.ValueFloat64()
			cfg.Slat.OpenTime = &v
		}
		if !wSlat.CloseTime.IsNull() && !wSlat.CloseTime.IsUnknown() {
			v := wSlat.CloseTime.ValueFloat64()
			cfg.Slat.CloseTime = &v
		}
		if !wSlat.Step.IsNull() && !wSlat.Step.IsUnknown() {
			v := wSlat.Step.ValueFloat64()
			cfg.Slat.Step = &v
		}
		if !wSlat.RetainPos.IsNull() && !wSlat.RetainPos.IsUnknown() {
			v := wSlat.RetainPos.ValueBool()
			cfg.Slat.RetainPos = &v
		}
		if !wSlat.PreciseCtl.IsNull() && !wSlat.PreciseCtl.IsUnknown() {
			v := wSlat.PreciseCtl.ValueBool()
			cfg.Slat.PreciseCtl = &v
		}
	}
	if !plan.SwapInputs.IsNull() && !plan.SwapInputs.IsUnknown() {
		v := plan.SwapInputs.ValueBool()
		cfg.SwapInputs = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.CoverSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *coverConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan coverConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *coverConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan coverConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *coverConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *coverConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
