// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &daliConfigResource{}
	_ resource.ResourceWithImportState = &daliConfigResource{}
)

func NewDALIConfigResource() resource.Resource { return &daliConfigResource{} }

type daliConfigResource struct{}

type daliConfigScanModel struct {
	CgCount   types.Float64 `tfsdk:"cg_count"`
	StartedAt types.Float64 `tfsdk:"started_at"`
}

type daliConfigResourceModel struct {
	IP      types.String         `tfsdk:"ip"`
	CgCount types.Float64        `tfsdk:"cg_count"`
	Scan    *daliConfigScanModel `tfsdk:"scan"`
	Errors  types.List           `tfsdk:"errors"`
}

func (r *daliConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dali_config"
}

func (r *daliConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"cg_count": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Number of scanned control gears (null if scan has never been executed)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"scan": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"cg_count": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Number of found control gears during scan",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"started_at": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Unix timestamp, start time of the scan process (in UTC)",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
			"errors": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Shown only if at least one error is present. May contain control_gear_missing, driver",
				PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *daliConfigResource) get(ctx context.Context, m *daliConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.DALIGetConfigRequest{}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.CgCount != nil {
		m.CgCount = types.Float64Value(*got.CgCount)
	}
	if got.Scan != nil {
		if m.Scan == nil {
			m.Scan = &daliConfigScanModel{}
		}
		if got.Scan.CgCount != nil {
			m.Scan.CgCount = types.Float64Value(*got.Scan.CgCount)
		}
		if got.Scan.StartedAt != nil {
			m.Scan.StartedAt = types.Float64Value(*got.Scan.StartedAt)
		}
	}
	if got.Errors != nil {
		l, d := types.ListValueFrom(ctx, types.StringType, got.Errors)
		diags.Append(d...)
		m.Errors = l
	}
}

func (r *daliConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state daliConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *daliConfigResource) apply(ctx context.Context, plan daliConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.DALIConfig
	if !plan.CgCount.IsNull() && !plan.CgCount.IsUnknown() {
		v := plan.CgCount.ValueFloat64()
		cfg.CgCount = &v
	}
	if plan.Scan != nil {
		cfg.Scan = &components.DALIConfigScan{}
		if !plan.Scan.CgCount.IsNull() && !plan.Scan.CgCount.IsUnknown() {
			v := plan.Scan.CgCount.ValueFloat64()
			cfg.Scan.CgCount = &v
		}
		if !plan.Scan.StartedAt.IsNull() && !plan.Scan.StartedAt.IsUnknown() {
			v := plan.Scan.StartedAt.ValueFloat64()
			cfg.Scan.StartedAt = &v
		}
	}
	if !plan.Errors.IsNull() && !plan.Errors.IsUnknown() {
		var v []string
		diags.Append(plan.Errors.ElementsAs(ctx, &v, false)...)
		cfg.Errors = v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.DALISetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *daliConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan daliConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *daliConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan daliConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *daliConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *daliConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
