// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &devicepowerConfigResource{}
	_ resource.ResourceWithImportState = &devicepowerConfigResource{}
)

func NewDevicePowerConfigResource() resource.Resource { return &devicepowerConfigResource{} }

type devicepowerConfigResource struct{}

type devicepowerConfigBatteryModel struct {
	Percent types.Float64 `tfsdk:"percent"`
}

type devicepowerConfigResourceModel struct {
	IP      types.String `tfsdk:"ip"`
	ID      types.Int64  `tfsdk:"id"`
	Battery types.Object `tfsdk:"battery"`
	Errors  types.List   `tfsdk:"errors"`
}

var devicepowerConfigBatteryAttrTypes = map[string]attr.Type{
	"percent": types.Float64Type,
}

func (r *devicepowerConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_devicepower_config"
}

func (r *devicepowerConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the DevicePower component instance."},
			"battery": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"percent": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Battery charge level in % (null if valid value could not be obtained)",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
			"errors": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Whether external power source is connected",
				PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *devicepowerConfigResource) get(ctx context.Context, m *devicepowerConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.DevicePowerGetConfigRequest{ID: int(m.ID.ValueInt64())}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Battery != nil {
		var sBattery devicepowerConfigBatteryModel
		if !m.Battery.IsNull() && !m.Battery.IsUnknown() {
			diags.Append(m.Battery.As(ctx, &sBattery, basetypes.ObjectAsOptions{})...)
		}
		if got.Battery.Percent != nil {
			sBattery.Percent = types.Float64Value(*got.Battery.Percent)
		} else if sBattery.Percent.IsUnknown() {
			sBattery.Percent = types.Float64Null()
		}
		oBattery, dBattery := types.ObjectValueFrom(ctx, devicepowerConfigBatteryAttrTypes, sBattery)
		diags.Append(dBattery...)
		m.Battery = oBattery
	} else {
		m.Battery = types.ObjectNull(devicepowerConfigBatteryAttrTypes)
	}
	if got.Errors != nil {
		l, d := types.ListValueFrom(ctx, types.StringType, got.Errors)
		diags.Append(d...)
		m.Errors = l
	} else if m.Errors.IsUnknown() {
		m.Errors = types.ListNull(types.StringType)
	}
}

func (r *devicepowerConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state devicepowerConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *devicepowerConfigResource) apply(ctx context.Context, plan devicepowerConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.DevicePowerConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Battery.IsNull() && !plan.Battery.IsUnknown() {
		var wBattery devicepowerConfigBatteryModel
		diags.Append(plan.Battery.As(ctx, &wBattery, basetypes.ObjectAsOptions{})...)
		cfg.Battery = &components.DevicePowerConfigBattery{}
		if !wBattery.Percent.IsNull() && !wBattery.Percent.IsUnknown() {
			v := wBattery.Percent.ValueFloat64()
			cfg.Battery.Percent = &v
		}
	}
	if !plan.Errors.IsNull() && !plan.Errors.IsUnknown() {
		var v []string
		diags.Append(plan.Errors.ElementsAs(ctx, &v, false)...)
		cfg.Errors = v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.DevicePowerSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *devicepowerConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan devicepowerConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *devicepowerConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan devicepowerConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *devicepowerConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *devicepowerConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
