// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &em1ConfigResource{}
	_ resource.ResourceWithImportState = &em1ConfigResource{}
)

func NewEM1ConfigResource() resource.Resource { return &em1ConfigResource{} }

type em1ConfigResource struct{}

type em1ConfigAlarmsModel struct {
	Voltage types.List `tfsdk:"voltage"`
	Current types.List `tfsdk:"current"`
	Power   types.List `tfsdk:"power"`
}

type em1ConfigResourceModel struct {
	IP      types.String `tfsdk:"ip"`
	ID      types.Int64  `tfsdk:"id"`
	Name    types.String `tfsdk:"name"`
	Reverse types.Bool   `tfsdk:"reverse"`
	CtType  types.String `tfsdk:"ct_type"`
	Alarms  types.Object `tfsdk:"alarms"`
}

var em1ConfigAlarmsAttrTypes = map[string]attr.Type{
	"voltage": types.ListType{ElemType: types.Float64Type},
	"current": types.ListType{ElemType: types.Float64Type},
	"power":   types.ListType{ElemType: types.Float64Type},
}

func (r *em1ConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_em1_config"
}

func (r *em1ConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the EM1 component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the EM1 instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"reverse": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Reverse CT measurement direction of active power and energy for the EM1 component. setting the reverse option requires restart",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"ct_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Select the type of Shelly current transformer attached to the device.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"alarms": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"voltage": schema.ListAttribute{
						ElementType:         types.Float64Type,
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "['under','over'] thresholds",
						PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
					},
					"current": schema.ListAttribute{
						ElementType:         types.Float64Type,
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "['under','over'] thresholds",
						PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
					},
					"power": schema.ListAttribute{
						ElementType:         types.Float64Type,
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "['under','over'] thresholds",
						PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
					},
				},
			},
		},
	}
}

func (r *em1ConfigResource) get(ctx context.Context, m *em1ConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.EM1GetConfigRequest{ID: int(m.ID.ValueInt64())}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		m.Name = types.StringValue(*got.Name)
	} else if m.Name.IsUnknown() {
		m.Name = types.StringNull()
	}
	if got.Reverse != nil {
		m.Reverse = types.BoolValue(*got.Reverse)
	} else if m.Reverse.IsUnknown() {
		m.Reverse = types.BoolNull()
	}
	if got.CtType != nil {
		m.CtType = types.StringValue(*got.CtType)
	} else if m.CtType.IsUnknown() {
		m.CtType = types.StringNull()
	}
	if got.Alarms != nil {
		var sAlarms em1ConfigAlarmsModel
		if !m.Alarms.IsNull() && !m.Alarms.IsUnknown() {
			diags.Append(m.Alarms.As(ctx, &sAlarms, basetypes.ObjectAsOptions{})...)
		}
		if got.Alarms.Voltage != nil {
			l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.Voltage)
			diags.Append(d...)
			sAlarms.Voltage = l
		} else if sAlarms.Voltage.IsUnknown() {
			sAlarms.Voltage = types.ListNull(types.Float64Type)
		}
		if got.Alarms.Current != nil {
			l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.Current)
			diags.Append(d...)
			sAlarms.Current = l
		} else if sAlarms.Current.IsUnknown() {
			sAlarms.Current = types.ListNull(types.Float64Type)
		}
		if got.Alarms.Power != nil {
			l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.Power)
			diags.Append(d...)
			sAlarms.Power = l
		} else if sAlarms.Power.IsUnknown() {
			sAlarms.Power = types.ListNull(types.Float64Type)
		}
		oAlarms, dAlarms := types.ObjectValueFrom(ctx, em1ConfigAlarmsAttrTypes, sAlarms)
		diags.Append(dAlarms...)
		m.Alarms = oAlarms
	} else {
		m.Alarms = types.ObjectNull(em1ConfigAlarmsAttrTypes)
	}
}

func (r *em1ConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state em1ConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *em1ConfigResource) apply(ctx context.Context, plan em1ConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.EM1Config
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.Reverse.IsNull() && !plan.Reverse.IsUnknown() {
		v := plan.Reverse.ValueBool()
		cfg.Reverse = &v
	}
	if !plan.CtType.IsNull() && !plan.CtType.IsUnknown() {
		v := plan.CtType.ValueString()
		cfg.CtType = &v
	}
	if !plan.Alarms.IsNull() && !plan.Alarms.IsUnknown() {
		var wAlarms em1ConfigAlarmsModel
		diags.Append(plan.Alarms.As(ctx, &wAlarms, basetypes.ObjectAsOptions{})...)
		cfg.Alarms = &components.EM1ConfigAlarms{}
		if !wAlarms.Voltage.IsNull() && !wAlarms.Voltage.IsUnknown() {
			var v []float64
			diags.Append(wAlarms.Voltage.ElementsAs(ctx, &v, false)...)
			cfg.Alarms.Voltage = v
		}
		if !wAlarms.Current.IsNull() && !wAlarms.Current.IsUnknown() {
			var v []float64
			diags.Append(wAlarms.Current.ElementsAs(ctx, &v, false)...)
			cfg.Alarms.Current = v
		}
		if !wAlarms.Power.IsNull() && !wAlarms.Power.IsUnknown() {
			var v []float64
			diags.Append(wAlarms.Power.ElementsAs(ctx, &v, false)...)
			cfg.Alarms.Power = v
		}
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.EM1SetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *em1ConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan em1ConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *em1ConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan em1ConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *em1ConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *em1ConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
