// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/go-shelly-lite"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &em1dataConfigResource{}
	_ resource.ResourceWithImportState = &em1dataConfigResource{}
)

func NewEM1DataConfigResource() resource.Resource { return &em1dataConfigResource{} }

type em1dataConfigResource struct{}

type em1dataConfigResourceModel struct {
	IP                types.String  `tfsdk:"ip"`
	ID                types.Int64   `tfsdk:"id"`
	TotalActEnergy    types.Float64 `tfsdk:"total_act_energy"`
	TotalActRetEnergy types.Float64 `tfsdk:"total_act_ret_energy"`
}

func (r *em1dataConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_em1data_config"
}

func (r *em1dataConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the EM1Data component instance."},
			"total_act_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active energy, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"total_act_ret_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active returned energy, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *em1dataConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state em1dataConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&shelly.EM1DataGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.TotalActEnergy != nil {
		state.TotalActEnergy = types.Float64Value(*got.TotalActEnergy)
	}
	if got.TotalActRetEnergy != nil {
		state.TotalActRetEnergy = types.Float64Value(*got.TotalActRetEnergy)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *em1dataConfigResource) apply(plan em1dataConfigResourceModel, diags *diag.Diagnostics) {
	var cfg shelly.EM1DataConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.TotalActEnergy.IsNull() && !plan.TotalActEnergy.IsUnknown() {
		v := plan.TotalActEnergy.ValueFloat64()
		cfg.TotalActEnergy = &v
	}
	if !plan.TotalActRetEnergy.IsNull() && !plan.TotalActRetEnergy.IsUnknown() {
		v := plan.TotalActRetEnergy.ValueFloat64()
		cfg.TotalActRetEnergy = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&shelly.EM1DataSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *em1dataConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan em1dataConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *em1dataConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan em1dataConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *em1dataConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *em1dataConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
