// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &emConfigResource{}
	_ resource.ResourceWithImportState = &emConfigResource{}
)

func NewEMConfigResource() resource.Resource { return &emConfigResource{} }

type emConfigResource struct{}

type emConfigReverseModel struct {
	A types.Bool `tfsdk:"a"`
	B types.Bool `tfsdk:"b"`
	C types.Bool `tfsdk:"c"`
}

type emConfigAlarmsAModel struct {
	Voltage types.List `tfsdk:"voltage"`
	Current types.List `tfsdk:"current"`
	Power   types.List `tfsdk:"power"`
}

type emConfigAlarmsBModel struct {
	Voltage types.List `tfsdk:"voltage"`
	Current types.List `tfsdk:"current"`
	Power   types.List `tfsdk:"power"`
}

type emConfigAlarmsCModel struct {
	Voltage types.List `tfsdk:"voltage"`
	Current types.List `tfsdk:"current"`
	Power   types.List `tfsdk:"power"`
}

type emConfigAlarmsModel struct {
	A types.Object `tfsdk:"a"`
	B types.Object `tfsdk:"b"`
	C types.Object `tfsdk:"c"`
}

type emConfigResourceModel struct {
	IP                   types.String `tfsdk:"ip"`
	ID                   types.Int64  `tfsdk:"id"`
	Name                 types.String `tfsdk:"name"`
	BlinkModeSelector    types.String `tfsdk:"blink_mode_selector"`
	PhaseSelector        types.String `tfsdk:"phase_selector"`
	MonitorPhaseSequence types.Bool   `tfsdk:"monitor_phase_sequence"`
	Reverse              types.Object `tfsdk:"reverse"`
	Alarms               types.Object `tfsdk:"alarms"`
	CtType               types.String `tfsdk:"ct_type"`
}

var emConfigReverseAttrTypes = map[string]attr.Type{
	"a": types.BoolType,
	"b": types.BoolType,
	"c": types.BoolType,
}

var emConfigAlarmsAAttrTypes = map[string]attr.Type{
	"voltage": types.ListType{ElemType: types.Float64Type},
	"current": types.ListType{ElemType: types.Float64Type},
	"power":   types.ListType{ElemType: types.Float64Type},
}

var emConfigAlarmsBAttrTypes = map[string]attr.Type{
	"voltage": types.ListType{ElemType: types.Float64Type},
	"current": types.ListType{ElemType: types.Float64Type},
	"power":   types.ListType{ElemType: types.Float64Type},
}

var emConfigAlarmsCAttrTypes = map[string]attr.Type{
	"voltage": types.ListType{ElemType: types.Float64Type},
	"current": types.ListType{ElemType: types.Float64Type},
	"power":   types.ListType{ElemType: types.Float64Type},
}

var emConfigAlarmsAttrTypes = map[string]attr.Type{
	"a": types.ObjectType{AttrTypes: emConfigAlarmsAAttrTypes},
	"b": types.ObjectType{AttrTypes: emConfigAlarmsBAttrTypes},
	"c": types.ObjectType{AttrTypes: emConfigAlarmsCAttrTypes},
}

func (r *emConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_em_config"
}

func (r *emConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the EM component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the energy meter instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"blink_mode_selector": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Select the electrical quantity that drives the LED. Range of values: active_energy, apparent_energy",
				Validators:          []validator.String{stringvalidator.OneOf("active_energy", "apparent_energy")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"phase_selector": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Select witch phase controls the LED. Range of values: a, b, c, all",
				Validators:          []validator.String{stringvalidator.OneOf("a", "b", "c", "all")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"monitor_phase_sequence": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Set this to show phase_sequence error in GetStatus if three-phase power system is used and the wires are not connected correctly to the device.",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"reverse": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"a": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "When set to true reverse CT measurement direction of active power and energy for phase A. shown if true",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"b": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "When set to true reverse CT measurement direction of active power and energy for phase B. shown if true",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"c": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "When set to true reverse CT measurement direction of active power and energy for phase C. shown if true",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
				},
			},
			"alarms": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"a": schema.SingleNestedAttribute{
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"voltage": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
							"current": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
							"power": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
						},
					},
					"b": schema.SingleNestedAttribute{
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"voltage": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
							"current": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
							"power": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
						},
					},
					"c": schema.SingleNestedAttribute{
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"voltage": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
							"current": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
							"power": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "['under','over'] thresholds",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
						},
					},
				},
			},
			"ct_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Select the type of Shelly current transformer attached to the device.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *emConfigResource) get(ctx context.Context, m *emConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.EMGetConfigRequest{ID: int(m.ID.ValueInt64())}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		m.Name = types.StringValue(*got.Name)
	} else if m.Name.IsUnknown() {
		m.Name = types.StringNull()
	}
	if got.BlinkModeSelector != nil {
		m.BlinkModeSelector = types.StringValue(*got.BlinkModeSelector)
	} else if m.BlinkModeSelector.IsUnknown() {
		m.BlinkModeSelector = types.StringNull()
	}
	if got.PhaseSelector != nil {
		m.PhaseSelector = types.StringValue(*got.PhaseSelector)
	} else if m.PhaseSelector.IsUnknown() {
		m.PhaseSelector = types.StringNull()
	}
	if got.MonitorPhaseSequence != nil {
		m.MonitorPhaseSequence = types.BoolValue(*got.MonitorPhaseSequence)
	} else if m.MonitorPhaseSequence.IsUnknown() {
		m.MonitorPhaseSequence = types.BoolNull()
	}
	if got.Reverse != nil {
		var sReverse emConfigReverseModel
		if !m.Reverse.IsNull() && !m.Reverse.IsUnknown() {
			diags.Append(m.Reverse.As(ctx, &sReverse, basetypes.ObjectAsOptions{})...)
		}
		if got.Reverse.A != nil {
			sReverse.A = types.BoolValue(*got.Reverse.A)
		} else if sReverse.A.IsUnknown() {
			sReverse.A = types.BoolNull()
		}
		if got.Reverse.B != nil {
			sReverse.B = types.BoolValue(*got.Reverse.B)
		} else if sReverse.B.IsUnknown() {
			sReverse.B = types.BoolNull()
		}
		if got.Reverse.C != nil {
			sReverse.C = types.BoolValue(*got.Reverse.C)
		} else if sReverse.C.IsUnknown() {
			sReverse.C = types.BoolNull()
		}
		oReverse, dReverse := types.ObjectValueFrom(ctx, emConfigReverseAttrTypes, sReverse)
		diags.Append(dReverse...)
		m.Reverse = oReverse
	} else {
		m.Reverse = types.ObjectNull(emConfigReverseAttrTypes)
	}
	if got.Alarms != nil {
		var sAlarms emConfigAlarmsModel
		if !m.Alarms.IsNull() && !m.Alarms.IsUnknown() {
			diags.Append(m.Alarms.As(ctx, &sAlarms, basetypes.ObjectAsOptions{})...)
		}
		if got.Alarms.A != nil {
			var sAlarmsA emConfigAlarmsAModel
			if !sAlarms.A.IsNull() && !sAlarms.A.IsUnknown() {
				diags.Append(sAlarms.A.As(ctx, &sAlarmsA, basetypes.ObjectAsOptions{})...)
			}
			if got.Alarms.A.Voltage != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.A.Voltage)
				diags.Append(d...)
				sAlarmsA.Voltage = l
			} else if sAlarmsA.Voltage.IsUnknown() {
				sAlarmsA.Voltage = types.ListNull(types.Float64Type)
			}
			if got.Alarms.A.Current != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.A.Current)
				diags.Append(d...)
				sAlarmsA.Current = l
			} else if sAlarmsA.Current.IsUnknown() {
				sAlarmsA.Current = types.ListNull(types.Float64Type)
			}
			if got.Alarms.A.Power != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.A.Power)
				diags.Append(d...)
				sAlarmsA.Power = l
			} else if sAlarmsA.Power.IsUnknown() {
				sAlarmsA.Power = types.ListNull(types.Float64Type)
			}
			oAlarmsA, dAlarmsA := types.ObjectValueFrom(ctx, emConfigAlarmsAAttrTypes, sAlarmsA)
			diags.Append(dAlarmsA...)
			sAlarms.A = oAlarmsA
		} else {
			sAlarms.A = types.ObjectNull(emConfigAlarmsAAttrTypes)
		}
		if got.Alarms.B != nil {
			var sAlarmsB emConfigAlarmsBModel
			if !sAlarms.B.IsNull() && !sAlarms.B.IsUnknown() {
				diags.Append(sAlarms.B.As(ctx, &sAlarmsB, basetypes.ObjectAsOptions{})...)
			}
			if got.Alarms.B.Voltage != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.B.Voltage)
				diags.Append(d...)
				sAlarmsB.Voltage = l
			} else if sAlarmsB.Voltage.IsUnknown() {
				sAlarmsB.Voltage = types.ListNull(types.Float64Type)
			}
			if got.Alarms.B.Current != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.B.Current)
				diags.Append(d...)
				sAlarmsB.Current = l
			} else if sAlarmsB.Current.IsUnknown() {
				sAlarmsB.Current = types.ListNull(types.Float64Type)
			}
			if got.Alarms.B.Power != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.B.Power)
				diags.Append(d...)
				sAlarmsB.Power = l
			} else if sAlarmsB.Power.IsUnknown() {
				sAlarmsB.Power = types.ListNull(types.Float64Type)
			}
			oAlarmsB, dAlarmsB := types.ObjectValueFrom(ctx, emConfigAlarmsBAttrTypes, sAlarmsB)
			diags.Append(dAlarmsB...)
			sAlarms.B = oAlarmsB
		} else {
			sAlarms.B = types.ObjectNull(emConfigAlarmsBAttrTypes)
		}
		if got.Alarms.C != nil {
			var sAlarmsC emConfigAlarmsCModel
			if !sAlarms.C.IsNull() && !sAlarms.C.IsUnknown() {
				diags.Append(sAlarms.C.As(ctx, &sAlarmsC, basetypes.ObjectAsOptions{})...)
			}
			if got.Alarms.C.Voltage != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.C.Voltage)
				diags.Append(d...)
				sAlarmsC.Voltage = l
			} else if sAlarmsC.Voltage.IsUnknown() {
				sAlarmsC.Voltage = types.ListNull(types.Float64Type)
			}
			if got.Alarms.C.Current != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.C.Current)
				diags.Append(d...)
				sAlarmsC.Current = l
			} else if sAlarmsC.Current.IsUnknown() {
				sAlarmsC.Current = types.ListNull(types.Float64Type)
			}
			if got.Alarms.C.Power != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.Alarms.C.Power)
				diags.Append(d...)
				sAlarmsC.Power = l
			} else if sAlarmsC.Power.IsUnknown() {
				sAlarmsC.Power = types.ListNull(types.Float64Type)
			}
			oAlarmsC, dAlarmsC := types.ObjectValueFrom(ctx, emConfigAlarmsCAttrTypes, sAlarmsC)
			diags.Append(dAlarmsC...)
			sAlarms.C = oAlarmsC
		} else {
			sAlarms.C = types.ObjectNull(emConfigAlarmsCAttrTypes)
		}
		oAlarms, dAlarms := types.ObjectValueFrom(ctx, emConfigAlarmsAttrTypes, sAlarms)
		diags.Append(dAlarms...)
		m.Alarms = oAlarms
	} else {
		m.Alarms = types.ObjectNull(emConfigAlarmsAttrTypes)
	}
	if got.CtType != nil {
		m.CtType = types.StringValue(*got.CtType)
	} else if m.CtType.IsUnknown() {
		m.CtType = types.StringNull()
	}
}

func (r *emConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state emConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *emConfigResource) apply(ctx context.Context, plan emConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.EMConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.BlinkModeSelector.IsNull() && !plan.BlinkModeSelector.IsUnknown() {
		v := plan.BlinkModeSelector.ValueString()
		cfg.BlinkModeSelector = &v
	}
	if !plan.PhaseSelector.IsNull() && !plan.PhaseSelector.IsUnknown() {
		v := plan.PhaseSelector.ValueString()
		cfg.PhaseSelector = &v
	}
	if !plan.MonitorPhaseSequence.IsNull() && !plan.MonitorPhaseSequence.IsUnknown() {
		v := plan.MonitorPhaseSequence.ValueBool()
		cfg.MonitorPhaseSequence = &v
	}
	if !plan.Reverse.IsNull() && !plan.Reverse.IsUnknown() {
		var wReverse emConfigReverseModel
		diags.Append(plan.Reverse.As(ctx, &wReverse, basetypes.ObjectAsOptions{})...)
		cfg.Reverse = &components.EMConfigReverse{}
		if !wReverse.A.IsNull() && !wReverse.A.IsUnknown() {
			v := wReverse.A.ValueBool()
			cfg.Reverse.A = &v
		}
		if !wReverse.B.IsNull() && !wReverse.B.IsUnknown() {
			v := wReverse.B.ValueBool()
			cfg.Reverse.B = &v
		}
		if !wReverse.C.IsNull() && !wReverse.C.IsUnknown() {
			v := wReverse.C.ValueBool()
			cfg.Reverse.C = &v
		}
	}
	if !plan.Alarms.IsNull() && !plan.Alarms.IsUnknown() {
		var wAlarms emConfigAlarmsModel
		diags.Append(plan.Alarms.As(ctx, &wAlarms, basetypes.ObjectAsOptions{})...)
		cfg.Alarms = &components.EMConfigAlarms{}
		if !wAlarms.A.IsNull() && !wAlarms.A.IsUnknown() {
			var wAlarmsA emConfigAlarmsAModel
			diags.Append(wAlarms.A.As(ctx, &wAlarmsA, basetypes.ObjectAsOptions{})...)
			cfg.Alarms.A = &components.EMConfigAlarmsA{}
			if !wAlarmsA.Voltage.IsNull() && !wAlarmsA.Voltage.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsA.Voltage.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.A.Voltage = v
			}
			if !wAlarmsA.Current.IsNull() && !wAlarmsA.Current.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsA.Current.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.A.Current = v
			}
			if !wAlarmsA.Power.IsNull() && !wAlarmsA.Power.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsA.Power.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.A.Power = v
			}
		}
		if !wAlarms.B.IsNull() && !wAlarms.B.IsUnknown() {
			var wAlarmsB emConfigAlarmsBModel
			diags.Append(wAlarms.B.As(ctx, &wAlarmsB, basetypes.ObjectAsOptions{})...)
			cfg.Alarms.B = &components.EMConfigAlarmsB{}
			if !wAlarmsB.Voltage.IsNull() && !wAlarmsB.Voltage.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsB.Voltage.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.B.Voltage = v
			}
			if !wAlarmsB.Current.IsNull() && !wAlarmsB.Current.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsB.Current.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.B.Current = v
			}
			if !wAlarmsB.Power.IsNull() && !wAlarmsB.Power.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsB.Power.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.B.Power = v
			}
		}
		if !wAlarms.C.IsNull() && !wAlarms.C.IsUnknown() {
			var wAlarmsC emConfigAlarmsCModel
			diags.Append(wAlarms.C.As(ctx, &wAlarmsC, basetypes.ObjectAsOptions{})...)
			cfg.Alarms.C = &components.EMConfigAlarmsC{}
			if !wAlarmsC.Voltage.IsNull() && !wAlarmsC.Voltage.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsC.Voltage.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.C.Voltage = v
			}
			if !wAlarmsC.Current.IsNull() && !wAlarmsC.Current.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsC.Current.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.C.Current = v
			}
			if !wAlarmsC.Power.IsNull() && !wAlarmsC.Power.IsUnknown() {
				var v []float64
				diags.Append(wAlarmsC.Power.ElementsAs(ctx, &v, false)...)
				cfg.Alarms.C.Power = v
			}
		}
	}
	if !plan.CtType.IsNull() && !plan.CtType.IsUnknown() {
		v := plan.CtType.ValueString()
		cfg.CtType = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.EMSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *emConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan emConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *emConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan emConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *emConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *emConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
