// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &emdataConfigResource{}
	_ resource.ResourceWithImportState = &emdataConfigResource{}
)

func NewEMDataConfigResource() resource.Resource { return &emdataConfigResource{} }

type emdataConfigResource struct{}

type emdataConfigResourceModel struct {
	IP                 types.String  `tfsdk:"ip"`
	ID                 types.Int64   `tfsdk:"id"`
	ATotalActEnergy    types.Float64 `tfsdk:"a_total_act_energy"`
	ATotalActRetEnergy types.Float64 `tfsdk:"a_total_act_ret_energy"`
	BTotalActEnergy    types.Float64 `tfsdk:"b_total_act_energy"`
	BTotalActRetEnergy types.Float64 `tfsdk:"b_total_act_ret_energy"`
	CTotalActEnergy    types.Float64 `tfsdk:"c_total_act_energy"`
	CTotalActRetEnergy types.Float64 `tfsdk:"c_total_act_ret_energy"`
	TotalAct           types.Float64 `tfsdk:"total_act"`
	TotalActRet        types.Float64 `tfsdk:"total_act_ret"`
}

func (r *emdataConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_emdata_config"
}

func (r *emdataConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the EMData component instance."},
			"a_total_act_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active energy on phase A, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"a_total_act_ret_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active returned energy on phase A, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"b_total_act_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active energy on phase B, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"b_total_act_ret_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active returned energy on phase B, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"c_total_act_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active energy on phase C, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"c_total_act_ret_energy": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active returned energy on phase C, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"total_act": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active energy on all phases, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"total_act_ret": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Total active returned energy on all phases, Wh",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *emdataConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state emdataConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&components.EMDataGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.ATotalActEnergy != nil {
		state.ATotalActEnergy = types.Float64Value(*got.ATotalActEnergy)
	}
	if got.ATotalActRetEnergy != nil {
		state.ATotalActRetEnergy = types.Float64Value(*got.ATotalActRetEnergy)
	}
	if got.BTotalActEnergy != nil {
		state.BTotalActEnergy = types.Float64Value(*got.BTotalActEnergy)
	}
	if got.BTotalActRetEnergy != nil {
		state.BTotalActRetEnergy = types.Float64Value(*got.BTotalActRetEnergy)
	}
	if got.CTotalActEnergy != nil {
		state.CTotalActEnergy = types.Float64Value(*got.CTotalActEnergy)
	}
	if got.CTotalActRetEnergy != nil {
		state.CTotalActRetEnergy = types.Float64Value(*got.CTotalActRetEnergy)
	}
	if got.TotalAct != nil {
		state.TotalAct = types.Float64Value(*got.TotalAct)
	}
	if got.TotalActRet != nil {
		state.TotalActRet = types.Float64Value(*got.TotalActRet)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *emdataConfigResource) apply(plan emdataConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.EMDataConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.ATotalActEnergy.IsNull() && !plan.ATotalActEnergy.IsUnknown() {
		v := plan.ATotalActEnergy.ValueFloat64()
		cfg.ATotalActEnergy = &v
	}
	if !plan.ATotalActRetEnergy.IsNull() && !plan.ATotalActRetEnergy.IsUnknown() {
		v := plan.ATotalActRetEnergy.ValueFloat64()
		cfg.ATotalActRetEnergy = &v
	}
	if !plan.BTotalActEnergy.IsNull() && !plan.BTotalActEnergy.IsUnknown() {
		v := plan.BTotalActEnergy.ValueFloat64()
		cfg.BTotalActEnergy = &v
	}
	if !plan.BTotalActRetEnergy.IsNull() && !plan.BTotalActRetEnergy.IsUnknown() {
		v := plan.BTotalActRetEnergy.ValueFloat64()
		cfg.BTotalActRetEnergy = &v
	}
	if !plan.CTotalActEnergy.IsNull() && !plan.CTotalActEnergy.IsUnknown() {
		v := plan.CTotalActEnergy.ValueFloat64()
		cfg.CTotalActEnergy = &v
	}
	if !plan.CTotalActRetEnergy.IsNull() && !plan.CTotalActRetEnergy.IsUnknown() {
		v := plan.CTotalActRetEnergy.ValueFloat64()
		cfg.CTotalActRetEnergy = &v
	}
	if !plan.TotalAct.IsNull() && !plan.TotalAct.IsUnknown() {
		v := plan.TotalAct.ValueFloat64()
		cfg.TotalAct = &v
	}
	if !plan.TotalActRet.IsNull() && !plan.TotalActRet.IsUnknown() {
		v := plan.TotalActRet.ValueFloat64()
		cfg.TotalActRet = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.EMDataSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *emdataConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan emdataConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *emdataConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan emdataConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *emdataConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *emdataConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
