// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &ethConfigResource{}
	_ resource.ResourceWithImportState = &ethConfigResource{}
)

func NewEthConfigResource() resource.Resource { return &ethConfigResource{} }

type ethConfigResource struct{}

type ethConfigResourceModel struct {
	IP         types.String `tfsdk:"ip"`
	Enable     types.Bool   `tfsdk:"enable"`
	ServerMode types.Bool   `tfsdk:"server_mode"`
	Ipv4mode   types.String `tfsdk:"ipv4mode"`
	Netmask    types.String `tfsdk:"netmask"`
	Gw         types.String `tfsdk:"gw"`
	Nameserver types.String `tfsdk:"nameserver"`
	DhcpStart  types.String `tfsdk:"dhcp_start"`
	DhcpEnd    types.String `tfsdk:"dhcp_end"`
}

func (r *ethConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_eth_config"
}

func (r *ethConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"enable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "true if the connection is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"server_mode": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "true if the inerface is configured to operate in server mode, false if in client mode",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"ipv4mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "IPv4 mode. Range of values: dhcp, static. Applicable only for client mode. Can be omitted if once set",
				Validators:          []validator.String{stringvalidator.OneOf("dhcp", "static")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"netmask": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Netmask of the network for client mode static and for server mode enabled. Optional, defaults to 255.255.255.0",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"gw": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Gateway of the network for client mode static and for server mode enabled. Optional, set to null to clear",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"nameserver": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Nameserver to use for client mode static and for server mode enabled. Optional, set to null to clear",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"dhcp_start": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "DHCP range starting IP address for the DHCP server in server mode. Applicable only for server mode. Required if not already set",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"dhcp_end": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "DHCP range ending IP address for the DHCP server in server mode. Applicable only for server mode. Required if not already set",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *ethConfigResource) get(ctx context.Context, m *ethConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.EthGetConfigRequest{}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Enable != nil {
		m.Enable = types.BoolValue(*got.Enable)
	}
	if got.ServerMode != nil {
		m.ServerMode = types.BoolValue(*got.ServerMode)
	}
	if got.Ipv4mode != nil {
		m.Ipv4mode = types.StringValue(*got.Ipv4mode)
	}
	if got.Netmask != nil {
		m.Netmask = types.StringValue(*got.Netmask)
	}
	if got.Gw != nil {
		m.Gw = types.StringValue(*got.Gw)
	}
	if got.Nameserver != nil {
		m.Nameserver = types.StringValue(*got.Nameserver)
	}
	if got.DhcpStart != nil {
		m.DhcpStart = types.StringValue(*got.DhcpStart)
	}
	if got.DhcpEnd != nil {
		m.DhcpEnd = types.StringValue(*got.DhcpEnd)
	}
}

func (r *ethConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ethConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ethConfigResource) apply(ctx context.Context, plan ethConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.EthConfig
	if !plan.Enable.IsNull() && !plan.Enable.IsUnknown() {
		v := plan.Enable.ValueBool()
		cfg.Enable = &v
	}
	if !plan.ServerMode.IsNull() && !plan.ServerMode.IsUnknown() {
		v := plan.ServerMode.ValueBool()
		cfg.ServerMode = &v
	}
	if !plan.Ipv4mode.IsNull() && !plan.Ipv4mode.IsUnknown() {
		v := plan.Ipv4mode.ValueString()
		cfg.Ipv4mode = &v
	}
	if !plan.Netmask.IsNull() && !plan.Netmask.IsUnknown() {
		v := plan.Netmask.ValueString()
		cfg.Netmask = &v
	}
	if !plan.Gw.IsNull() && !plan.Gw.IsUnknown() {
		v := plan.Gw.ValueString()
		cfg.Gw = &v
	}
	if !plan.Nameserver.IsNull() && !plan.Nameserver.IsUnknown() {
		v := plan.Nameserver.ValueString()
		cfg.Nameserver = &v
	}
	if !plan.DhcpStart.IsNull() && !plan.DhcpStart.IsUnknown() {
		v := plan.DhcpStart.ValueString()
		cfg.DhcpStart = &v
	}
	if !plan.DhcpEnd.IsNull() && !plan.DhcpEnd.IsUnknown() {
		v := plan.DhcpEnd.ValueString()
		cfg.DhcpEnd = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.EthSetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *ethConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ethConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ethConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ethConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ethConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *ethConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
