// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &illuminanceConfigResource{}
	_ resource.ResourceWithImportState = &illuminanceConfigResource{}
)

func NewIlluminanceConfigResource() resource.Resource { return &illuminanceConfigResource{} }

type illuminanceConfigResource struct{}

type illuminanceConfigResourceModel struct {
	IP        types.String  `tfsdk:"ip"`
	ID        types.Int64   `tfsdk:"id"`
	Name      types.String  `tfsdk:"name"`
	DarkThr   types.Float64 `tfsdk:"dark_thr"`
	BrightThr types.Float64 `tfsdk:"bright_thr"`
}

func (r *illuminanceConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_illuminance_config"
}

func (r *illuminanceConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the Illuminance component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the Illuminance instance. name length should not exceed 64 chars",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"dark_thr": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Threshold in lux. Accepted range is device-specific",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"bright_thr": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "bright threshold in lux. Accepted range is device-specific",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *illuminanceConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state illuminanceConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&components.IlluminanceGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		state.Name = types.StringValue(*got.Name)
	}
	if got.DarkThr != nil {
		state.DarkThr = types.Float64Value(*got.DarkThr)
	}
	if got.BrightThr != nil {
		state.BrightThr = types.Float64Value(*got.BrightThr)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *illuminanceConfigResource) apply(plan illuminanceConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.IlluminanceConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.DarkThr.IsNull() && !plan.DarkThr.IsUnknown() {
		v := plan.DarkThr.ValueFloat64()
		cfg.DarkThr = &v
	}
	if !plan.BrightThr.IsNull() && !plan.BrightThr.IsUnknown() {
		v := plan.BrightThr.ValueFloat64()
		cfg.BrightThr = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.IlluminanceSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *illuminanceConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan illuminanceConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *illuminanceConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan illuminanceConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *illuminanceConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *illuminanceConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
