// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/float64validator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &inputConfigResource{}
	_ resource.ResourceWithImportState = &inputConfigResource{}
)

func NewInputConfigResource() resource.Resource { return &inputConfigResource{} }

type inputConfigResource struct{}

type inputConfigXpercentModel struct {
	Expr types.String `tfsdk:"expr"`
	Unit types.String `tfsdk:"unit"`
}

type inputConfigXcountsModel struct {
	Expr types.String `tfsdk:"expr"`
	Unit types.String `tfsdk:"unit"`
}

type inputConfigXfreqModel struct {
	Expr types.String `tfsdk:"expr"`
	Unit types.String `tfsdk:"unit"`
}

type inputConfigResourceModel struct {
	IP           types.String  `tfsdk:"ip"`
	ID           types.Int64   `tfsdk:"id"`
	Name         types.String  `tfsdk:"name"`
	Type         types.String  `tfsdk:"type"`
	Enable       types.Bool    `tfsdk:"enable"`
	Invert       types.Bool    `tfsdk:"invert"`
	FactoryReset types.Bool    `tfsdk:"factory_reset"`
	ReportThr    types.Float64 `tfsdk:"report_thr"`
	Range        types.Float64 `tfsdk:"range"`
	Xpercent     types.Object  `tfsdk:"xpercent"`
	CountRepThr  types.Float64 `tfsdk:"count_rep_thr"`
	FreqWindow   types.Float64 `tfsdk:"freq_window"`
	FreqRepThr   types.Float64 `tfsdk:"freq_rep_thr"`
	Xcounts      types.Object  `tfsdk:"xcounts"`
	Xfreq        types.Object  `tfsdk:"xfreq"`
}

var inputConfigXpercentAttrTypes = map[string]attr.Type{
	"expr": types.StringType,
	"unit": types.StringType,
}

var inputConfigXcountsAttrTypes = map[string]attr.Type{
	"expr": types.StringType,
	"unit": types.StringType,
}

var inputConfigXfreqAttrTypes = map[string]attr.Type{
	"expr": types.StringType,
	"unit": types.StringType,
}

func (r *inputConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_input_config"
}

func (r *inputConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the Input component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the input instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Type of associated input. Range of values switch, button, analog, count (only if applicable).",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Global enable flag. When disabled, the input instance doesn't emit any events and reports status properties as null. Applies for all input types",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"invert": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "(only for type switch, button, analog) True if the logical state of the associated input is inverted, false otherwise. For the change to be applied, the physical switch has to be toggled once after invert is set. For type analog inverts percent range - 100% becomes 0% and 0% becomes 100%",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"factory_reset": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "(only for type switch, button) True if input-triggered factory reset option is enabled, false otherwise (shown if applicable)",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"report_thr": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "(only for type analog) Analog input report threshold in percent. The accepted range is device-specific, default [1.0..50.0]% unless specified otherwise",
				Validators:          []validator.Float64{float64validator.Between(1, 50)},
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"range": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "(only for type analog) Analog input range, which is device-specific. See the table below.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"xpercent": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"expr": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "JS expression containing x, where x is the raw value to be transformed (status.percent), for example \"x+1\". Accepted range: null or [0..100] chars. Both null and \"\" mean value transformation is disabled.",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"unit": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Unit of the transformed value (status.xpercent), for example, \"m/s\". Accepted range: null or [0..20] chars. Both null and \"\" mean value transformation is disabled.",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
				},
			},
			"count_rep_thr": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "(only for type count) Counts report threshold in number of pulses. Accepted range [1 - 2147483647]",
				Validators:          []validator.Float64{float64validator.Between(1, 2147483647)},
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"freq_window": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "(only for type count) Reference time in seconds for base of frequency measurement. Accepted range [1 - 3600]",
				Validators:          []validator.Float64{float64validator.Between(1, 3600)},
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"freq_rep_thr": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "(only for type count) Frequency report threshold in percent. Accepted range [0 - 10000]",
				Validators:          []validator.Float64{float64validator.Between(0, 10000)},
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"xcounts": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"expr": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "JS expression containing x, where x is the raw value to be transformed (status.counts.total and status.counts.by_minute), for example \"x+1\". Accepted range: null or [0..100] chars. Both null and \"\" mean value transformation is disabled.",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"unit": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Unit of the transformed values (status.counts.xtotal and status.counts.xby_minute), for example, \"m/s\". Accepted range: null or [0..20] chars. Both null and \"\" mean value transformation is disabled.",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
				},
			},
			"xfreq": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"expr": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "JS expression containing x, where x is the raw value to be transformed (status.freq), for example \"x+1\". Accepted range: null or [0..100] chars. Both null and \"\" mean value transformation is disabled.",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"unit": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Unit of the transformed value (status.xfreq), for example, \"m/s\". Accepted range: null or [0..20] chars. Both null and \"\" mean value transformation is disabled.",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
				},
			},
		},
	}
}

func (r *inputConfigResource) get(ctx context.Context, m *inputConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.InputGetConfigRequest{ID: int(m.ID.ValueInt64())}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		m.Name = types.StringValue(*got.Name)
	} else if m.Name.IsUnknown() {
		m.Name = types.StringNull()
	}
	if got.Type != nil {
		m.Type = types.StringValue(*got.Type)
	} else if m.Type.IsUnknown() {
		m.Type = types.StringNull()
	}
	if got.Enable != nil {
		m.Enable = types.BoolValue(*got.Enable)
	} else if m.Enable.IsUnknown() {
		m.Enable = types.BoolNull()
	}
	if got.Invert != nil {
		m.Invert = types.BoolValue(*got.Invert)
	} else if m.Invert.IsUnknown() {
		m.Invert = types.BoolNull()
	}
	if got.FactoryReset != nil {
		m.FactoryReset = types.BoolValue(*got.FactoryReset)
	} else if m.FactoryReset.IsUnknown() {
		m.FactoryReset = types.BoolNull()
	}
	if got.ReportThr != nil {
		m.ReportThr = types.Float64Value(*got.ReportThr)
	} else if m.ReportThr.IsUnknown() {
		m.ReportThr = types.Float64Null()
	}
	if got.Range != nil {
		m.Range = types.Float64Value(*got.Range)
	} else if m.Range.IsUnknown() {
		m.Range = types.Float64Null()
	}
	if got.Xpercent != nil {
		var sXpercent inputConfigXpercentModel
		if !m.Xpercent.IsNull() && !m.Xpercent.IsUnknown() {
			diags.Append(m.Xpercent.As(ctx, &sXpercent, basetypes.ObjectAsOptions{})...)
		}
		if got.Xpercent.Expr != nil {
			sXpercent.Expr = types.StringValue(*got.Xpercent.Expr)
		} else if sXpercent.Expr.IsUnknown() {
			sXpercent.Expr = types.StringNull()
		}
		if got.Xpercent.Unit != nil {
			sXpercent.Unit = types.StringValue(*got.Xpercent.Unit)
		} else if sXpercent.Unit.IsUnknown() {
			sXpercent.Unit = types.StringNull()
		}
		oXpercent, dXpercent := types.ObjectValueFrom(ctx, inputConfigXpercentAttrTypes, sXpercent)
		diags.Append(dXpercent...)
		m.Xpercent = oXpercent
	} else {
		m.Xpercent = types.ObjectNull(inputConfigXpercentAttrTypes)
	}
	if got.CountRepThr != nil {
		m.CountRepThr = types.Float64Value(*got.CountRepThr)
	} else if m.CountRepThr.IsUnknown() {
		m.CountRepThr = types.Float64Null()
	}
	if got.FreqWindow != nil {
		m.FreqWindow = types.Float64Value(*got.FreqWindow)
	} else if m.FreqWindow.IsUnknown() {
		m.FreqWindow = types.Float64Null()
	}
	if got.FreqRepThr != nil {
		m.FreqRepThr = types.Float64Value(*got.FreqRepThr)
	} else if m.FreqRepThr.IsUnknown() {
		m.FreqRepThr = types.Float64Null()
	}
	if got.Xcounts != nil {
		var sXcounts inputConfigXcountsModel
		if !m.Xcounts.IsNull() && !m.Xcounts.IsUnknown() {
			diags.Append(m.Xcounts.As(ctx, &sXcounts, basetypes.ObjectAsOptions{})...)
		}
		if got.Xcounts.Expr != nil {
			sXcounts.Expr = types.StringValue(*got.Xcounts.Expr)
		} else if sXcounts.Expr.IsUnknown() {
			sXcounts.Expr = types.StringNull()
		}
		if got.Xcounts.Unit != nil {
			sXcounts.Unit = types.StringValue(*got.Xcounts.Unit)
		} else if sXcounts.Unit.IsUnknown() {
			sXcounts.Unit = types.StringNull()
		}
		oXcounts, dXcounts := types.ObjectValueFrom(ctx, inputConfigXcountsAttrTypes, sXcounts)
		diags.Append(dXcounts...)
		m.Xcounts = oXcounts
	} else {
		m.Xcounts = types.ObjectNull(inputConfigXcountsAttrTypes)
	}
	if got.Xfreq != nil {
		var sXfreq inputConfigXfreqModel
		if !m.Xfreq.IsNull() && !m.Xfreq.IsUnknown() {
			diags.Append(m.Xfreq.As(ctx, &sXfreq, basetypes.ObjectAsOptions{})...)
		}
		if got.Xfreq.Expr != nil {
			sXfreq.Expr = types.StringValue(*got.Xfreq.Expr)
		} else if sXfreq.Expr.IsUnknown() {
			sXfreq.Expr = types.StringNull()
		}
		if got.Xfreq.Unit != nil {
			sXfreq.Unit = types.StringValue(*got.Xfreq.Unit)
		} else if sXfreq.Unit.IsUnknown() {
			sXfreq.Unit = types.StringNull()
		}
		oXfreq, dXfreq := types.ObjectValueFrom(ctx, inputConfigXfreqAttrTypes, sXfreq)
		diags.Append(dXfreq...)
		m.Xfreq = oXfreq
	} else {
		m.Xfreq = types.ObjectNull(inputConfigXfreqAttrTypes)
	}
}

func (r *inputConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state inputConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *inputConfigResource) apply(ctx context.Context, plan inputConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.InputConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.Type.IsNull() && !plan.Type.IsUnknown() {
		v := plan.Type.ValueString()
		cfg.Type = &v
	}
	if !plan.Enable.IsNull() && !plan.Enable.IsUnknown() {
		v := plan.Enable.ValueBool()
		cfg.Enable = &v
	}
	if !plan.Invert.IsNull() && !plan.Invert.IsUnknown() {
		v := plan.Invert.ValueBool()
		cfg.Invert = &v
	}
	if !plan.FactoryReset.IsNull() && !plan.FactoryReset.IsUnknown() {
		v := plan.FactoryReset.ValueBool()
		cfg.FactoryReset = &v
	}
	if !plan.ReportThr.IsNull() && !plan.ReportThr.IsUnknown() {
		v := plan.ReportThr.ValueFloat64()
		cfg.ReportThr = &v
	}
	if !plan.Range.IsNull() && !plan.Range.IsUnknown() {
		v := plan.Range.ValueFloat64()
		cfg.Range = &v
	}
	if !plan.Xpercent.IsNull() && !plan.Xpercent.IsUnknown() {
		var wXpercent inputConfigXpercentModel
		diags.Append(plan.Xpercent.As(ctx, &wXpercent, basetypes.ObjectAsOptions{})...)
		cfg.Xpercent = &components.InputConfigXpercent{}
		if !wXpercent.Expr.IsNull() && !wXpercent.Expr.IsUnknown() {
			v := wXpercent.Expr.ValueString()
			cfg.Xpercent.Expr = &v
		}
		if !wXpercent.Unit.IsNull() && !wXpercent.Unit.IsUnknown() {
			v := wXpercent.Unit.ValueString()
			cfg.Xpercent.Unit = &v
		}
	}
	if !plan.CountRepThr.IsNull() && !plan.CountRepThr.IsUnknown() {
		v := plan.CountRepThr.ValueFloat64()
		cfg.CountRepThr = &v
	}
	if !plan.FreqWindow.IsNull() && !plan.FreqWindow.IsUnknown() {
		v := plan.FreqWindow.ValueFloat64()
		cfg.FreqWindow = &v
	}
	if !plan.FreqRepThr.IsNull() && !plan.FreqRepThr.IsUnknown() {
		v := plan.FreqRepThr.ValueFloat64()
		cfg.FreqRepThr = &v
	}
	if !plan.Xcounts.IsNull() && !plan.Xcounts.IsUnknown() {
		var wXcounts inputConfigXcountsModel
		diags.Append(plan.Xcounts.As(ctx, &wXcounts, basetypes.ObjectAsOptions{})...)
		cfg.Xcounts = &components.InputConfigXcounts{}
		if !wXcounts.Expr.IsNull() && !wXcounts.Expr.IsUnknown() {
			v := wXcounts.Expr.ValueString()
			cfg.Xcounts.Expr = &v
		}
		if !wXcounts.Unit.IsNull() && !wXcounts.Unit.IsUnknown() {
			v := wXcounts.Unit.ValueString()
			cfg.Xcounts.Unit = &v
		}
	}
	if !plan.Xfreq.IsNull() && !plan.Xfreq.IsUnknown() {
		var wXfreq inputConfigXfreqModel
		diags.Append(plan.Xfreq.As(ctx, &wXfreq, basetypes.ObjectAsOptions{})...)
		cfg.Xfreq = &components.InputConfigXfreq{}
		if !wXfreq.Expr.IsNull() && !wXfreq.Expr.IsUnknown() {
			v := wXfreq.Expr.ValueString()
			cfg.Xfreq.Expr = &v
		}
		if !wXfreq.Unit.IsNull() && !wXfreq.Unit.IsUnknown() {
			v := wXfreq.Unit.ValueString()
			cfg.Xfreq.Unit = &v
		}
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.InputSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *inputConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan inputConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *inputConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan inputConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *inputConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *inputConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
