// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/float64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &lightConfigResource{}
	_ resource.ResourceWithImportState = &lightConfigResource{}
)

func NewLightConfigResource() resource.Resource { return &lightConfigResource{} }

type lightConfigResource struct{}

type lightConfigNightModeModel struct {
	Enable     types.Bool    `tfsdk:"enable"`
	Brightness types.Float64 `tfsdk:"brightness"`
}

type lightConfigButtonPresetsButtonDoublepushModel struct {
	Brightness types.Float64 `tfsdk:"brightness"`
}

type lightConfigButtonPresetsModel struct {
	ButtonDoublepush types.Object `tfsdk:"button_doublepush"`
}

type lightConfigWarmupModel struct {
	Enable     types.Bool    `tfsdk:"enable"`
	Brightness types.Float64 `tfsdk:"brightness"`
	TimeMs     types.Float64 `tfsdk:"time_ms"`
}

type lightConfigResourceModel struct {
	IP                    types.String  `tfsdk:"ip"`
	ID                    types.Int64   `tfsdk:"id"`
	Name                  types.String  `tfsdk:"name"`
	InMode                types.String  `tfsdk:"in_mode"`
	OpMode                types.Float64 `tfsdk:"op_mode"`
	InitialState          types.String  `tfsdk:"initial_state"`
	AutoOn                types.Bool    `tfsdk:"auto_on"`
	AutoOnDelay           types.Float64 `tfsdk:"auto_on_delay"`
	AutoOff               types.Bool    `tfsdk:"auto_off"`
	AutoOffDelay          types.Float64 `tfsdk:"auto_off_delay"`
	TransitionDuration    types.Float64 `tfsdk:"transition_duration"`
	Gamma                 types.Float64 `tfsdk:"gamma"`
	MinBrightnessOnToggle types.Float64 `tfsdk:"min_brightness_on_toggle"`
	NightMode             types.Object  `tfsdk:"night_mode"`
	ButtonFadeRate        types.Float64 `tfsdk:"button_fade_rate"`
	ButtonPresets         types.Object  `tfsdk:"button_presets"`
	PowerLimit            types.Float64 `tfsdk:"power_limit"`
	VoltageLimit          types.Float64 `tfsdk:"voltage_limit"`
	UndervoltageLimit     types.Float64 `tfsdk:"undervoltage_limit"`
	CurrentLimit          types.Float64 `tfsdk:"current_limit"`
	Warmup                types.Object  `tfsdk:"warmup"`
}

var lightConfigNightModeAttrTypes = map[string]attr.Type{
	"enable":     types.BoolType,
	"brightness": types.Float64Type,
}

var lightConfigButtonPresetsButtonDoublepushAttrTypes = map[string]attr.Type{
	"brightness": types.Float64Type,
}

var lightConfigButtonPresetsAttrTypes = map[string]attr.Type{
	"button_doublepush": types.ObjectType{AttrTypes: lightConfigButtonPresetsButtonDoublepushAttrTypes},
}

var lightConfigWarmupAttrTypes = map[string]attr.Type{
	"enable":     types.BoolType,
	"brightness": types.Float64Type,
	"time_ms":    types.Float64Type,
}

func (r *lightConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_light_config"
}

func (r *lightConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the Light component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the light instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"in_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Mode of the associated input. Range of values: follow, flip, activate, detached, dim (if applicable), dual_dim (if applicable)",
				Validators:          []validator.String{stringvalidator.OneOf("follow", "flip", "activate", "detached", "dim")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"op_mode": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Operational mode (if applicable), which is device-specific. See the table below.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"initial_state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Output state to set on power_on. Range of values: off, on, restore_last, toggle",
				Validators:          []validator.String{stringvalidator.OneOf("off", "on", "restore_last", "toggle")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"auto_on": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic ON\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_on_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back on",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"auto_off": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic OFF\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_off_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back off",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"transition_duration": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Transition time (in seconds) - time to change from 0% to 100% of brightness (if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"gamma": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Gamma correction (dimensionless) - adjusts light intensity for perceptual linearity. Range 0.4 to 4.0, default 1.0 (if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"min_brightness_on_toggle": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Brightness level (in percent) applied when there is a toggle and current brightness is lower than min_brightness_on_toggle.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"night_mode": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Enable or disable night mode",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"brightness": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Brightness level limit when night mode is active. Default value 50.",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
			"button_fade_rate": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Controls how quickly the output level changes while a button is held down for dimming (if applicable). Default value 3. Range [1,5] where 5 is fastest, 1 is slowest",
				Validators:          []validator.Float64{float64validator.Between(1, 5)},
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"button_presets": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"button_doublepush": schema.SingleNestedAttribute{
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"brightness": schema.Float64Attribute{
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "Brightness level (in percent) set on double click (if applicable), default: 100",
								PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
							},
						},
					},
				},
			},
			"power_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Watts) over which overpower condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"voltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Volts) over which overvoltage condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"undervoltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Volts) under which undervoltage condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"current_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Amperes) over which overcurrent condition occurs (shown if applicable). For PlusRGBWPM shown if device is calibrated.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"warmup": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "When enabled warmup is applied on toogle from off to on and brightness below 10%.",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"brightness": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Warmup brightness in percent. Range 10-100%.",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"time_ms": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Time period during which warmup_brightness will be on. Range 20-1000 milliseconds.",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
		},
	}
}

func (r *lightConfigResource) get(ctx context.Context, m *lightConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.LightGetConfigRequest{ID: int(m.ID.ValueInt64())}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		m.Name = types.StringValue(*got.Name)
	} else if m.Name.IsUnknown() {
		m.Name = types.StringNull()
	}
	if got.InMode != nil {
		m.InMode = types.StringValue(*got.InMode)
	} else if m.InMode.IsUnknown() {
		m.InMode = types.StringNull()
	}
	if got.OpMode != nil {
		m.OpMode = types.Float64Value(*got.OpMode)
	} else if m.OpMode.IsUnknown() {
		m.OpMode = types.Float64Null()
	}
	if got.InitialState != nil {
		m.InitialState = types.StringValue(*got.InitialState)
	} else if m.InitialState.IsUnknown() {
		m.InitialState = types.StringNull()
	}
	if got.AutoOn != nil {
		m.AutoOn = types.BoolValue(*got.AutoOn)
	} else if m.AutoOn.IsUnknown() {
		m.AutoOn = types.BoolNull()
	}
	if got.AutoOnDelay != nil {
		m.AutoOnDelay = types.Float64Value(*got.AutoOnDelay)
	} else if m.AutoOnDelay.IsUnknown() {
		m.AutoOnDelay = types.Float64Null()
	}
	if got.AutoOff != nil {
		m.AutoOff = types.BoolValue(*got.AutoOff)
	} else if m.AutoOff.IsUnknown() {
		m.AutoOff = types.BoolNull()
	}
	if got.AutoOffDelay != nil {
		m.AutoOffDelay = types.Float64Value(*got.AutoOffDelay)
	} else if m.AutoOffDelay.IsUnknown() {
		m.AutoOffDelay = types.Float64Null()
	}
	if got.TransitionDuration != nil {
		m.TransitionDuration = types.Float64Value(*got.TransitionDuration)
	} else if m.TransitionDuration.IsUnknown() {
		m.TransitionDuration = types.Float64Null()
	}
	if got.Gamma != nil {
		m.Gamma = types.Float64Value(*got.Gamma)
	} else if m.Gamma.IsUnknown() {
		m.Gamma = types.Float64Null()
	}
	if got.MinBrightnessOnToggle != nil {
		m.MinBrightnessOnToggle = types.Float64Value(*got.MinBrightnessOnToggle)
	} else if m.MinBrightnessOnToggle.IsUnknown() {
		m.MinBrightnessOnToggle = types.Float64Null()
	}
	if got.NightMode != nil {
		var sNightMode lightConfigNightModeModel
		if !m.NightMode.IsNull() && !m.NightMode.IsUnknown() {
			diags.Append(m.NightMode.As(ctx, &sNightMode, basetypes.ObjectAsOptions{})...)
		}
		if got.NightMode.Enable != nil {
			sNightMode.Enable = types.BoolValue(*got.NightMode.Enable)
		} else if sNightMode.Enable.IsUnknown() {
			sNightMode.Enable = types.BoolNull()
		}
		if got.NightMode.Brightness != nil {
			sNightMode.Brightness = types.Float64Value(*got.NightMode.Brightness)
		} else if sNightMode.Brightness.IsUnknown() {
			sNightMode.Brightness = types.Float64Null()
		}
		oNightMode, dNightMode := types.ObjectValueFrom(ctx, lightConfigNightModeAttrTypes, sNightMode)
		diags.Append(dNightMode...)
		m.NightMode = oNightMode
	} else {
		m.NightMode = types.ObjectNull(lightConfigNightModeAttrTypes)
	}
	if got.ButtonFadeRate != nil {
		m.ButtonFadeRate = types.Float64Value(*got.ButtonFadeRate)
	} else if m.ButtonFadeRate.IsUnknown() {
		m.ButtonFadeRate = types.Float64Null()
	}
	if got.ButtonPresets != nil {
		var sButtonPresets lightConfigButtonPresetsModel
		if !m.ButtonPresets.IsNull() && !m.ButtonPresets.IsUnknown() {
			diags.Append(m.ButtonPresets.As(ctx, &sButtonPresets, basetypes.ObjectAsOptions{})...)
		}
		if got.ButtonPresets.ButtonDoublepush != nil {
			var sButtonPresetsButtonDoublepush lightConfigButtonPresetsButtonDoublepushModel
			if !sButtonPresets.ButtonDoublepush.IsNull() && !sButtonPresets.ButtonDoublepush.IsUnknown() {
				diags.Append(sButtonPresets.ButtonDoublepush.As(ctx, &sButtonPresetsButtonDoublepush, basetypes.ObjectAsOptions{})...)
			}
			if got.ButtonPresets.ButtonDoublepush.Brightness != nil {
				sButtonPresetsButtonDoublepush.Brightness = types.Float64Value(*got.ButtonPresets.ButtonDoublepush.Brightness)
			} else if sButtonPresetsButtonDoublepush.Brightness.IsUnknown() {
				sButtonPresetsButtonDoublepush.Brightness = types.Float64Null()
			}
			oButtonPresetsButtonDoublepush, dButtonPresetsButtonDoublepush := types.ObjectValueFrom(ctx, lightConfigButtonPresetsButtonDoublepushAttrTypes, sButtonPresetsButtonDoublepush)
			diags.Append(dButtonPresetsButtonDoublepush...)
			sButtonPresets.ButtonDoublepush = oButtonPresetsButtonDoublepush
		} else {
			sButtonPresets.ButtonDoublepush = types.ObjectNull(lightConfigButtonPresetsButtonDoublepushAttrTypes)
		}
		oButtonPresets, dButtonPresets := types.ObjectValueFrom(ctx, lightConfigButtonPresetsAttrTypes, sButtonPresets)
		diags.Append(dButtonPresets...)
		m.ButtonPresets = oButtonPresets
	} else {
		m.ButtonPresets = types.ObjectNull(lightConfigButtonPresetsAttrTypes)
	}
	if got.PowerLimit != nil {
		m.PowerLimit = types.Float64Value(*got.PowerLimit)
	} else if m.PowerLimit.IsUnknown() {
		m.PowerLimit = types.Float64Null()
	}
	if got.VoltageLimit != nil {
		m.VoltageLimit = types.Float64Value(*got.VoltageLimit)
	} else if m.VoltageLimit.IsUnknown() {
		m.VoltageLimit = types.Float64Null()
	}
	if got.UndervoltageLimit != nil {
		m.UndervoltageLimit = types.Float64Value(*got.UndervoltageLimit)
	} else if m.UndervoltageLimit.IsUnknown() {
		m.UndervoltageLimit = types.Float64Null()
	}
	if got.CurrentLimit != nil {
		m.CurrentLimit = types.Float64Value(*got.CurrentLimit)
	} else if m.CurrentLimit.IsUnknown() {
		m.CurrentLimit = types.Float64Null()
	}
	if got.Warmup != nil {
		var sWarmup lightConfigWarmupModel
		if !m.Warmup.IsNull() && !m.Warmup.IsUnknown() {
			diags.Append(m.Warmup.As(ctx, &sWarmup, basetypes.ObjectAsOptions{})...)
		}
		if got.Warmup.Enable != nil {
			sWarmup.Enable = types.BoolValue(*got.Warmup.Enable)
		} else if sWarmup.Enable.IsUnknown() {
			sWarmup.Enable = types.BoolNull()
		}
		if got.Warmup.Brightness != nil {
			sWarmup.Brightness = types.Float64Value(*got.Warmup.Brightness)
		} else if sWarmup.Brightness.IsUnknown() {
			sWarmup.Brightness = types.Float64Null()
		}
		if got.Warmup.TimeMs != nil {
			sWarmup.TimeMs = types.Float64Value(*got.Warmup.TimeMs)
		} else if sWarmup.TimeMs.IsUnknown() {
			sWarmup.TimeMs = types.Float64Null()
		}
		oWarmup, dWarmup := types.ObjectValueFrom(ctx, lightConfigWarmupAttrTypes, sWarmup)
		diags.Append(dWarmup...)
		m.Warmup = oWarmup
	} else {
		m.Warmup = types.ObjectNull(lightConfigWarmupAttrTypes)
	}
}

func (r *lightConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state lightConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *lightConfigResource) apply(ctx context.Context, plan lightConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.LightConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.InMode.IsNull() && !plan.InMode.IsUnknown() {
		v := plan.InMode.ValueString()
		cfg.InMode = &v
	}
	if !plan.OpMode.IsNull() && !plan.OpMode.IsUnknown() {
		v := plan.OpMode.ValueFloat64()
		cfg.OpMode = &v
	}
	if !plan.InitialState.IsNull() && !plan.InitialState.IsUnknown() {
		v := plan.InitialState.ValueString()
		cfg.InitialState = &v
	}
	if !plan.AutoOn.IsNull() && !plan.AutoOn.IsUnknown() {
		v := plan.AutoOn.ValueBool()
		cfg.AutoOn = &v
	}
	if !plan.AutoOnDelay.IsNull() && !plan.AutoOnDelay.IsUnknown() {
		v := plan.AutoOnDelay.ValueFloat64()
		cfg.AutoOnDelay = &v
	}
	if !plan.AutoOff.IsNull() && !plan.AutoOff.IsUnknown() {
		v := plan.AutoOff.ValueBool()
		cfg.AutoOff = &v
	}
	if !plan.AutoOffDelay.IsNull() && !plan.AutoOffDelay.IsUnknown() {
		v := plan.AutoOffDelay.ValueFloat64()
		cfg.AutoOffDelay = &v
	}
	if !plan.TransitionDuration.IsNull() && !plan.TransitionDuration.IsUnknown() {
		v := plan.TransitionDuration.ValueFloat64()
		cfg.TransitionDuration = &v
	}
	if !plan.Gamma.IsNull() && !plan.Gamma.IsUnknown() {
		v := plan.Gamma.ValueFloat64()
		cfg.Gamma = &v
	}
	if !plan.MinBrightnessOnToggle.IsNull() && !plan.MinBrightnessOnToggle.IsUnknown() {
		v := plan.MinBrightnessOnToggle.ValueFloat64()
		cfg.MinBrightnessOnToggle = &v
	}
	if !plan.NightMode.IsNull() && !plan.NightMode.IsUnknown() {
		var wNightMode lightConfigNightModeModel
		diags.Append(plan.NightMode.As(ctx, &wNightMode, basetypes.ObjectAsOptions{})...)
		cfg.NightMode = &components.LightConfigNightMode{}
		if !wNightMode.Enable.IsNull() && !wNightMode.Enable.IsUnknown() {
			v := wNightMode.Enable.ValueBool()
			cfg.NightMode.Enable = &v
		}
		if !wNightMode.Brightness.IsNull() && !wNightMode.Brightness.IsUnknown() {
			v := wNightMode.Brightness.ValueFloat64()
			cfg.NightMode.Brightness = &v
		}
	}
	if !plan.ButtonFadeRate.IsNull() && !plan.ButtonFadeRate.IsUnknown() {
		v := plan.ButtonFadeRate.ValueFloat64()
		cfg.ButtonFadeRate = &v
	}
	if !plan.ButtonPresets.IsNull() && !plan.ButtonPresets.IsUnknown() {
		var wButtonPresets lightConfigButtonPresetsModel
		diags.Append(plan.ButtonPresets.As(ctx, &wButtonPresets, basetypes.ObjectAsOptions{})...)
		cfg.ButtonPresets = &components.LightConfigButtonPresets{}
		if !wButtonPresets.ButtonDoublepush.IsNull() && !wButtonPresets.ButtonDoublepush.IsUnknown() {
			var wButtonPresetsButtonDoublepush lightConfigButtonPresetsButtonDoublepushModel
			diags.Append(wButtonPresets.ButtonDoublepush.As(ctx, &wButtonPresetsButtonDoublepush, basetypes.ObjectAsOptions{})...)
			cfg.ButtonPresets.ButtonDoublepush = &components.LightConfigButtonPresetsButtonDoublepush{}
			if !wButtonPresetsButtonDoublepush.Brightness.IsNull() && !wButtonPresetsButtonDoublepush.Brightness.IsUnknown() {
				v := wButtonPresetsButtonDoublepush.Brightness.ValueFloat64()
				cfg.ButtonPresets.ButtonDoublepush.Brightness = &v
			}
		}
	}
	if !plan.PowerLimit.IsNull() && !plan.PowerLimit.IsUnknown() {
		v := plan.PowerLimit.ValueFloat64()
		cfg.PowerLimit = &v
	}
	if !plan.VoltageLimit.IsNull() && !plan.VoltageLimit.IsUnknown() {
		v := plan.VoltageLimit.ValueFloat64()
		cfg.VoltageLimit = &v
	}
	if !plan.UndervoltageLimit.IsNull() && !plan.UndervoltageLimit.IsUnknown() {
		v := plan.UndervoltageLimit.ValueFloat64()
		cfg.UndervoltageLimit = &v
	}
	if !plan.CurrentLimit.IsNull() && !plan.CurrentLimit.IsUnknown() {
		v := plan.CurrentLimit.ValueFloat64()
		cfg.CurrentLimit = &v
	}
	if !plan.Warmup.IsNull() && !plan.Warmup.IsUnknown() {
		var wWarmup lightConfigWarmupModel
		diags.Append(plan.Warmup.As(ctx, &wWarmup, basetypes.ObjectAsOptions{})...)
		cfg.Warmup = &components.LightConfigWarmup{}
		if !wWarmup.Enable.IsNull() && !wWarmup.Enable.IsUnknown() {
			v := wWarmup.Enable.ValueBool()
			cfg.Warmup.Enable = &v
		}
		if !wWarmup.Brightness.IsNull() && !wWarmup.Brightness.IsUnknown() {
			v := wWarmup.Brightness.ValueFloat64()
			cfg.Warmup.Brightness = &v
		}
		if !wWarmup.TimeMs.IsNull() && !wWarmup.TimeMs.IsUnknown() {
			v := wWarmup.TimeMs.ValueFloat64()
			cfg.Warmup.TimeMs = &v
		}
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.LightSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *lightConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan lightConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *lightConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan lightConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *lightConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *lightConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
