// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/go-shelly-lite"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &lightConfigResource{}
	_ resource.ResourceWithImportState = &lightConfigResource{}
)

func NewLightConfigResource() resource.Resource { return &lightConfigResource{} }

type lightConfigResource struct{}

type lightConfigResourceModel struct {
	IP                    types.String  `tfsdk:"ip"`
	ID                    types.Int64   `tfsdk:"id"`
	Name                  types.String  `tfsdk:"name"`
	InMode                types.String  `tfsdk:"in_mode"`
	OpMode                types.Float64 `tfsdk:"op_mode"`
	InitialState          types.String  `tfsdk:"initial_state"`
	AutoOn                types.Bool    `tfsdk:"auto_on"`
	AutoOnDelay           types.Float64 `tfsdk:"auto_on_delay"`
	AutoOff               types.Bool    `tfsdk:"auto_off"`
	AutoOffDelay          types.Float64 `tfsdk:"auto_off_delay"`
	TransitionDuration    types.Float64 `tfsdk:"transition_duration"`
	Gamma                 types.Float64 `tfsdk:"gamma"`
	MinBrightnessOnToggle types.Float64 `tfsdk:"min_brightness_on_toggle"`
	ButtonFadeRate        types.Float64 `tfsdk:"button_fade_rate"`
	PowerLimit            types.Float64 `tfsdk:"power_limit"`
	VoltageLimit          types.Float64 `tfsdk:"voltage_limit"`
	UndervoltageLimit     types.Float64 `tfsdk:"undervoltage_limit"`
	CurrentLimit          types.Float64 `tfsdk:"current_limit"`
}

func (r *lightConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_light_config"
}

func (r *lightConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the Light component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the light instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"in_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Mode of the associated input. Range of values: follow, flip, activate, detached, dim (if applicable), dual_dim (if applicable)",
				Validators:          []validator.String{stringvalidator.OneOf("follow", "flip", "activate", "detached", "dim")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"op_mode": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Operational mode (if applicable), which is device-specific. See the table below.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"initial_state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Output state to set on power_on. Range of values: off, on, restore_last, toggle",
				Validators:          []validator.String{stringvalidator.OneOf("off", "on", "restore_last", "toggle")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"auto_on": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic ON\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_on_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back on",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"auto_off": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic OFF\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_off_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back off",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"transition_duration": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Transition time (in seconds) - time to change from 0% to 100% of brightness (if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"gamma": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Gamma correction (dimensionless) - adjusts light intensity for perceptual linearity. Range 0.4 to 4.0, default 1.0 (if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"min_brightness_on_toggle": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Brightness level (in percent) applied when there is a toggle and current brightness is lower than min_brightness_on_toggle.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"button_fade_rate": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Controls how quickly the output level changes while a button is held down for dimming (if applicable). Default value 3. Range [1,5] where 5 is fastest, 1 is slowest",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"power_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Watts) over which overpower condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"voltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Volts) over which overvoltage condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"undervoltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Volts) under which undervoltage condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"current_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Amperes) over which overcurrent condition occurs (shown if applicable). For PlusRGBWPM shown if device is calibrated.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *lightConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state lightConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&shelly.LightGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		state.Name = types.StringValue(*got.Name)
	}
	if got.InMode != nil {
		state.InMode = types.StringValue(*got.InMode)
	}
	if got.OpMode != nil {
		state.OpMode = types.Float64Value(*got.OpMode)
	}
	if got.InitialState != nil {
		state.InitialState = types.StringValue(*got.InitialState)
	}
	if got.AutoOn != nil {
		state.AutoOn = types.BoolValue(*got.AutoOn)
	}
	if got.AutoOnDelay != nil {
		state.AutoOnDelay = types.Float64Value(*got.AutoOnDelay)
	}
	if got.AutoOff != nil {
		state.AutoOff = types.BoolValue(*got.AutoOff)
	}
	if got.AutoOffDelay != nil {
		state.AutoOffDelay = types.Float64Value(*got.AutoOffDelay)
	}
	if got.TransitionDuration != nil {
		state.TransitionDuration = types.Float64Value(*got.TransitionDuration)
	}
	if got.Gamma != nil {
		state.Gamma = types.Float64Value(*got.Gamma)
	}
	if got.MinBrightnessOnToggle != nil {
		state.MinBrightnessOnToggle = types.Float64Value(*got.MinBrightnessOnToggle)
	}
	if got.ButtonFadeRate != nil {
		state.ButtonFadeRate = types.Float64Value(*got.ButtonFadeRate)
	}
	if got.PowerLimit != nil {
		state.PowerLimit = types.Float64Value(*got.PowerLimit)
	}
	if got.VoltageLimit != nil {
		state.VoltageLimit = types.Float64Value(*got.VoltageLimit)
	}
	if got.UndervoltageLimit != nil {
		state.UndervoltageLimit = types.Float64Value(*got.UndervoltageLimit)
	}
	if got.CurrentLimit != nil {
		state.CurrentLimit = types.Float64Value(*got.CurrentLimit)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *lightConfigResource) apply(plan lightConfigResourceModel, diags *diag.Diagnostics) {
	var cfg shelly.LightConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.InMode.IsNull() && !plan.InMode.IsUnknown() {
		v := plan.InMode.ValueString()
		cfg.InMode = &v
	}
	if !plan.OpMode.IsNull() && !plan.OpMode.IsUnknown() {
		v := plan.OpMode.ValueFloat64()
		cfg.OpMode = &v
	}
	if !plan.InitialState.IsNull() && !plan.InitialState.IsUnknown() {
		v := plan.InitialState.ValueString()
		cfg.InitialState = &v
	}
	if !plan.AutoOn.IsNull() && !plan.AutoOn.IsUnknown() {
		v := plan.AutoOn.ValueBool()
		cfg.AutoOn = &v
	}
	if !plan.AutoOnDelay.IsNull() && !plan.AutoOnDelay.IsUnknown() {
		v := plan.AutoOnDelay.ValueFloat64()
		cfg.AutoOnDelay = &v
	}
	if !plan.AutoOff.IsNull() && !plan.AutoOff.IsUnknown() {
		v := plan.AutoOff.ValueBool()
		cfg.AutoOff = &v
	}
	if !plan.AutoOffDelay.IsNull() && !plan.AutoOffDelay.IsUnknown() {
		v := plan.AutoOffDelay.ValueFloat64()
		cfg.AutoOffDelay = &v
	}
	if !plan.TransitionDuration.IsNull() && !plan.TransitionDuration.IsUnknown() {
		v := plan.TransitionDuration.ValueFloat64()
		cfg.TransitionDuration = &v
	}
	if !plan.Gamma.IsNull() && !plan.Gamma.IsUnknown() {
		v := plan.Gamma.ValueFloat64()
		cfg.Gamma = &v
	}
	if !plan.MinBrightnessOnToggle.IsNull() && !plan.MinBrightnessOnToggle.IsUnknown() {
		v := plan.MinBrightnessOnToggle.ValueFloat64()
		cfg.MinBrightnessOnToggle = &v
	}
	if !plan.ButtonFadeRate.IsNull() && !plan.ButtonFadeRate.IsUnknown() {
		v := plan.ButtonFadeRate.ValueFloat64()
		cfg.ButtonFadeRate = &v
	}
	if !plan.PowerLimit.IsNull() && !plan.PowerLimit.IsUnknown() {
		v := plan.PowerLimit.ValueFloat64()
		cfg.PowerLimit = &v
	}
	if !plan.VoltageLimit.IsNull() && !plan.VoltageLimit.IsUnknown() {
		v := plan.VoltageLimit.ValueFloat64()
		cfg.VoltageLimit = &v
	}
	if !plan.UndervoltageLimit.IsNull() && !plan.UndervoltageLimit.IsUnknown() {
		v := plan.UndervoltageLimit.ValueFloat64()
		cfg.UndervoltageLimit = &v
	}
	if !plan.CurrentLimit.IsNull() && !plan.CurrentLimit.IsUnknown() {
		v := plan.CurrentLimit.ValueFloat64()
		cfg.CurrentLimit = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&shelly.LightSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *lightConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan lightConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *lightConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan lightConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *lightConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *lightConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
