// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/shelly-go"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &mqttConfigResource{}
	_ resource.ResourceWithImportState = &mqttConfigResource{}
)

func NewMQTTConfigResource() resource.Resource { return &mqttConfigResource{} }

type mqttConfigResource struct{}

type mqttConfigResourceModel struct {
	IP            types.String `tfsdk:"ip"`
	Enable        types.Bool   `tfsdk:"enable"`
	Server        types.String `tfsdk:"server"`
	User          types.String `tfsdk:"user"`
	RPCNtf        types.Bool   `tfsdk:"rpc_ntf"`
	StatusNtf     types.Bool   `tfsdk:"status_ntf"`
	UseClientCert types.Bool   `tfsdk:"use_client_cert"`
	EnableControl types.Bool   `tfsdk:"enable_control"`
}

func (r *mqttConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mqtt_config"
}

func (r *mqttConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"enable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if MQTT connection is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"server": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Host name of the MQTT server. Can be followed by port number - host:port",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"user": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Username",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"rpc_ntf": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Enables RPC notifications (NotifyStatus and NotifyEvent) to be published on <device_id|topic_prefix>/events/rpc (<topic_prefix> when a custom prefix is set, <device_id> otherwise). Default value: true.",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"status_ntf": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Enables publishing the complete component status on <device_id|topic_prefix>/status/<component>:<id> (<topic_prefix> when a custom prefix is set, <device_id> otherwise). The complete status will be published if a signifficant change occurred. Default value: false",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"use_client_cert": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Enable or diable usage of client certifactes to use MQTT with encription, default: false",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"enable_control": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Enable the MQTT control feature. Defalut value: true",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *mqttConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state mqttConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&shelly.MQTTGetConfigRequest{}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Enable != nil {
		state.Enable = types.BoolValue(*got.Enable)
	}
	if got.Server != nil {
		state.Server = types.StringValue(*got.Server)
	}
	if got.User != nil {
		state.User = types.StringValue(*got.User)
	}
	if got.RPCNtf != nil {
		state.RPCNtf = types.BoolValue(*got.RPCNtf)
	}
	if got.StatusNtf != nil {
		state.StatusNtf = types.BoolValue(*got.StatusNtf)
	}
	if got.UseClientCert != nil {
		state.UseClientCert = types.BoolValue(*got.UseClientCert)
	}
	if got.EnableControl != nil {
		state.EnableControl = types.BoolValue(*got.EnableControl)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *mqttConfigResource) apply(plan mqttConfigResourceModel, diags *diag.Diagnostics) {
	var cfg shelly.MQTTConfig
	if !plan.Enable.IsNull() && !plan.Enable.IsUnknown() {
		v := plan.Enable.ValueBool()
		cfg.Enable = &v
	}
	if !plan.Server.IsNull() && !plan.Server.IsUnknown() {
		v := plan.Server.ValueString()
		cfg.Server = &v
	}
	if !plan.User.IsNull() && !plan.User.IsUnknown() {
		v := plan.User.ValueString()
		cfg.User = &v
	}
	if !plan.RPCNtf.IsNull() && !plan.RPCNtf.IsUnknown() {
		v := plan.RPCNtf.ValueBool()
		cfg.RPCNtf = &v
	}
	if !plan.StatusNtf.IsNull() && !plan.StatusNtf.IsUnknown() {
		v := plan.StatusNtf.ValueBool()
		cfg.StatusNtf = &v
	}
	if !plan.UseClientCert.IsNull() && !plan.UseClientCert.IsUnknown() {
		v := plan.UseClientCert.ValueBool()
		cfg.UseClientCert = &v
	}
	if !plan.EnableControl.IsNull() && !plan.EnableControl.IsUnknown() {
		v := plan.EnableControl.ValueBool()
		cfg.EnableControl = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&shelly.MQTTSetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *mqttConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan mqttConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mqttConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan mqttConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *mqttConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *mqttConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
