// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &pillConfigResource{}
	_ resource.ResourceWithImportState = &pillConfigResource{}
)

func NewPillConfigResource() resource.Resource { return &pillConfigResource{} }

type pillConfigResource struct{}

type pillConfigResourceModel struct {
	IP       types.String `tfsdk:"ip"`
	Mode     types.String `tfsdk:"mode"`
	Pin0Mode types.String `tfsdk:"pin0_mode"`
	Pin1Mode types.String `tfsdk:"pin1_mode"`
	Pin2Mode types.String `tfsdk:"pin2_mode"`
}

func (r *pillConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pill_config"
}

func (r *pillConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Device mode. Range of values onewire, dht22, analog_in, ssr, digital_io",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"pin0_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Pin 0 mode. Range of values none, reserved, digital_in, digital_out",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"pin1_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Pin 1 mode. Range of values none, reserved, digital_in, digital_out",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"pin2_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Pin 2 mode. Range of values none, reserved, digital_in, digital_out",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *pillConfigResource) get(ctx context.Context, m *pillConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.PillGetConfigRequest{}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Mode != nil {
		m.Mode = types.StringValue(*got.Mode)
	}
	if got.Pin0Mode != nil {
		m.Pin0Mode = types.StringValue(*got.Pin0Mode)
	}
	if got.Pin1Mode != nil {
		m.Pin1Mode = types.StringValue(*got.Pin1Mode)
	}
	if got.Pin2Mode != nil {
		m.Pin2Mode = types.StringValue(*got.Pin2Mode)
	}
}

func (r *pillConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state pillConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *pillConfigResource) apply(ctx context.Context, plan pillConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.PillConfig
	if !plan.Mode.IsNull() && !plan.Mode.IsUnknown() {
		v := plan.Mode.ValueString()
		cfg.Mode = &v
	}
	if !plan.Pin0Mode.IsNull() && !plan.Pin0Mode.IsUnknown() {
		v := plan.Pin0Mode.ValueString()
		cfg.Pin0Mode = &v
	}
	if !plan.Pin1Mode.IsNull() && !plan.Pin1Mode.IsUnknown() {
		v := plan.Pin1Mode.ValueString()
		cfg.Pin1Mode = &v
	}
	if !plan.Pin2Mode.IsNull() && !plan.Pin2Mode.IsUnknown() {
		v := plan.Pin2Mode.ValueString()
		cfg.Pin2Mode = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.PillSetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *pillConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan pillConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *pillConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan pillConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *pillConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *pillConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
