// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &presencezoneConfigResource{}
	_ resource.ResourceWithImportState = &presencezoneConfigResource{}
)

func NewPresenceZoneConfigResource() resource.Resource { return &presencezoneConfigResource{} }

type presencezoneConfigResource struct{}

type presencezoneConfigResourceModel struct {
	IP            types.String  `tfsdk:"ip"`
	ID            types.Int64   `tfsdk:"id"`
	Name          types.String  `tfsdk:"name"`
	Enable        types.Bool    `tfsdk:"enable"`
	PresenceDelay types.Float64 `tfsdk:"presence_delay"`
	AbsenceDelay  types.Float64 `tfsdk:"absence_delay"`
}

func (r *presencezoneConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_presencezone_config"
}

func (r *presencezoneConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the PresenceZone component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the component instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"enable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Activate or deactivate zone",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"presence_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Active period of presence before trigger (in seconds)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"absence_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Active period of absence before trigger (in seconds)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *presencezoneConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state presencezoneConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&components.PresenceZoneGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		state.Name = types.StringValue(*got.Name)
	}
	if got.Enable != nil {
		state.Enable = types.BoolValue(*got.Enable)
	}
	if got.PresenceDelay != nil {
		state.PresenceDelay = types.Float64Value(*got.PresenceDelay)
	}
	if got.AbsenceDelay != nil {
		state.AbsenceDelay = types.Float64Value(*got.AbsenceDelay)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *presencezoneConfigResource) apply(plan presencezoneConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.PresenceZoneConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.Enable.IsNull() && !plan.Enable.IsUnknown() {
		v := plan.Enable.ValueBool()
		cfg.Enable = &v
	}
	if !plan.PresenceDelay.IsNull() && !plan.PresenceDelay.IsUnknown() {
		v := plan.PresenceDelay.ValueFloat64()
		cfg.PresenceDelay = &v
	}
	if !plan.AbsenceDelay.IsNull() && !plan.AbsenceDelay.IsUnknown() {
		v := plan.AbsenceDelay.ValueFloat64()
		cfg.AbsenceDelay = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.PresenceZoneSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *presencezoneConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan presencezoneConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *presencezoneConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan presencezoneConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *presencezoneConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *presencezoneConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
