// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/go-shelly-lite"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &presenceConfigResource{}
	_ resource.ResourceWithImportState = &presenceConfigResource{}
)

func NewPresenceConfigResource() resource.Resource { return &presenceConfigResource{} }

type presenceConfigResource struct{}

type presenceConfigResourceModel struct {
	IP       types.String  `tfsdk:"ip"`
	Enable   types.Bool    `tfsdk:"enable"`
	Zmin     types.Float64 `tfsdk:"zmin"`
	Zmax     types.Float64 `tfsdk:"zmax"`
	MainZone types.String  `tfsdk:"main_zone"`
}

func (r *presenceConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_presence_config"
}

func (r *presenceConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"enable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Enable or disable tracking sensor",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"zmin": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Lower detection limit in meters",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"zmax": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Upper detection limit in meters",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"main_zone": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Default presence zone key. (readonly)",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *presenceConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state presenceConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&shelly.PresenceGetConfigRequest{}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Enable != nil {
		state.Enable = types.BoolValue(*got.Enable)
	}
	if got.Zmin != nil {
		state.Zmin = types.Float64Value(*got.Zmin)
	}
	if got.Zmax != nil {
		state.Zmax = types.Float64Value(*got.Zmax)
	}
	if got.MainZone != nil {
		state.MainZone = types.StringValue(*got.MainZone)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *presenceConfigResource) apply(plan presenceConfigResourceModel, diags *diag.Diagnostics) {
	var cfg shelly.PresenceConfig
	if !plan.Enable.IsNull() && !plan.Enable.IsUnknown() {
		v := plan.Enable.ValueBool()
		cfg.Enable = &v
	}
	if !plan.Zmin.IsNull() && !plan.Zmin.IsUnknown() {
		v := plan.Zmin.ValueFloat64()
		cfg.Zmin = &v
	}
	if !plan.Zmax.IsNull() && !plan.Zmax.IsUnknown() {
		v := plan.Zmax.ValueFloat64()
		cfg.Zmax = &v
	}
	if !plan.MainZone.IsNull() && !plan.MainZone.IsUnknown() {
		v := plan.MainZone.ValueString()
		cfg.MainZone = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&shelly.PresenceSetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *presenceConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan presenceConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *presenceConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan presenceConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *presenceConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *presenceConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
