// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &rgbcctConfigResource{}
	_ resource.ResourceWithImportState = &rgbcctConfigResource{}
)

func NewRGBCCTConfigResource() resource.Resource { return &rgbcctConfigResource{} }

type rgbcctConfigResource struct{}

type rgbcctConfigNightModeModel struct {
	Enable     types.Bool    `tfsdk:"enable"`
	Brightness types.Float64 `tfsdk:"brightness"`
	Ct         types.Float64 `tfsdk:"ct"`
	Mode       types.String  `tfsdk:"mode"`
}

type rgbcctConfigResourceModel struct {
	IP                    types.String                `tfsdk:"ip"`
	ID                    types.Int64                 `tfsdk:"id"`
	Name                  types.String                `tfsdk:"name"`
	InitialState          types.String                `tfsdk:"initial_state"`
	AutoOn                types.Bool                  `tfsdk:"auto_on"`
	AutoOnDelay           types.Float64               `tfsdk:"auto_on_delay"`
	AutoOff               types.Bool                  `tfsdk:"auto_off"`
	AutoOffDelay          types.Float64               `tfsdk:"auto_off_delay"`
	TransitionDuration    types.Float64               `tfsdk:"transition_duration"`
	MinBrightnessOnToggle types.Float64               `tfsdk:"min_brightness_on_toggle"`
	NightMode             *rgbcctConfigNightModeModel `tfsdk:"night_mode"`
}

func (r *rgbcctConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_rgbcct_config"
}

func (r *rgbcctConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the RGBCCT component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the RGBCCT instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"initial_state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Output state to set on power_on. Range of values: off, on, restore_last",
				Validators:          []validator.String{stringvalidator.OneOf("off", "on", "restore_last")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"auto_on": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic ON\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_on_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back on",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"auto_off": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic OFF\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_off_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back off",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"transition_duration": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Transition time (in seconds) - time to change from 0% to 100% of brightness, RGB levels or color temperature value",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"min_brightness_on_toggle": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Brightness level (in percent) applied when there is a toggle and current brightness is lower than min_brightness_on_toggle.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"night_mode": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Enable or disable night mode",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"brightness": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Brightness level limit (in percent) when night mode is active. null overrides night_mode.brightness with current brightness when night mode starts. Default value 50.",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"ct": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Color temperature level limit (in Kelvin) when night mode is active. null overrides night_mode.ct value with current ct value when night mode starts. Default value: 50% of ct_range. For DuoBulbG3: 4600",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"mode": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Operating mode of the light output when night mode is active. Range of values: rgb, cct or null. null overrides night_mode.mode value with current mode when night mode starts. Default value: rgb",
						Validators:          []validator.String{stringvalidator.OneOf("rgb")},
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
				},
			},
		},
	}
}

func (r *rgbcctConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state rgbcctConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&components.RGBCCTGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		state.Name = types.StringValue(*got.Name)
	}
	if got.InitialState != nil {
		state.InitialState = types.StringValue(*got.InitialState)
	}
	if got.AutoOn != nil {
		state.AutoOn = types.BoolValue(*got.AutoOn)
	}
	if got.AutoOnDelay != nil {
		state.AutoOnDelay = types.Float64Value(*got.AutoOnDelay)
	}
	if got.AutoOff != nil {
		state.AutoOff = types.BoolValue(*got.AutoOff)
	}
	if got.AutoOffDelay != nil {
		state.AutoOffDelay = types.Float64Value(*got.AutoOffDelay)
	}
	if got.TransitionDuration != nil {
		state.TransitionDuration = types.Float64Value(*got.TransitionDuration)
	}
	if got.MinBrightnessOnToggle != nil {
		state.MinBrightnessOnToggle = types.Float64Value(*got.MinBrightnessOnToggle)
	}
	if got.NightMode != nil {
		if state.NightMode == nil {
			state.NightMode = &rgbcctConfigNightModeModel{}
		}
		if got.NightMode.Enable != nil {
			state.NightMode.Enable = types.BoolValue(*got.NightMode.Enable)
		}
		if got.NightMode.Brightness != nil {
			state.NightMode.Brightness = types.Float64Value(*got.NightMode.Brightness)
		}
		if got.NightMode.Ct != nil {
			state.NightMode.Ct = types.Float64Value(*got.NightMode.Ct)
		}
		if got.NightMode.Mode != nil {
			state.NightMode.Mode = types.StringValue(*got.NightMode.Mode)
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *rgbcctConfigResource) apply(plan rgbcctConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.RGBCCTConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.InitialState.IsNull() && !plan.InitialState.IsUnknown() {
		v := plan.InitialState.ValueString()
		cfg.InitialState = &v
	}
	if !plan.AutoOn.IsNull() && !plan.AutoOn.IsUnknown() {
		v := plan.AutoOn.ValueBool()
		cfg.AutoOn = &v
	}
	if !plan.AutoOnDelay.IsNull() && !plan.AutoOnDelay.IsUnknown() {
		v := plan.AutoOnDelay.ValueFloat64()
		cfg.AutoOnDelay = &v
	}
	if !plan.AutoOff.IsNull() && !plan.AutoOff.IsUnknown() {
		v := plan.AutoOff.ValueBool()
		cfg.AutoOff = &v
	}
	if !plan.AutoOffDelay.IsNull() && !plan.AutoOffDelay.IsUnknown() {
		v := plan.AutoOffDelay.ValueFloat64()
		cfg.AutoOffDelay = &v
	}
	if !plan.TransitionDuration.IsNull() && !plan.TransitionDuration.IsUnknown() {
		v := plan.TransitionDuration.ValueFloat64()
		cfg.TransitionDuration = &v
	}
	if !plan.MinBrightnessOnToggle.IsNull() && !plan.MinBrightnessOnToggle.IsUnknown() {
		v := plan.MinBrightnessOnToggle.ValueFloat64()
		cfg.MinBrightnessOnToggle = &v
	}
	if plan.NightMode != nil {
		cfg.NightMode = &components.RGBCCTConfigNightMode{}
		if !plan.NightMode.Enable.IsNull() && !plan.NightMode.Enable.IsUnknown() {
			v := plan.NightMode.Enable.ValueBool()
			cfg.NightMode.Enable = &v
		}
		if !plan.NightMode.Brightness.IsNull() && !plan.NightMode.Brightness.IsUnknown() {
			v := plan.NightMode.Brightness.ValueFloat64()
			cfg.NightMode.Brightness = &v
		}
		if !plan.NightMode.Ct.IsNull() && !plan.NightMode.Ct.IsUnknown() {
			v := plan.NightMode.Ct.ValueFloat64()
			cfg.NightMode.Ct = &v
		}
		if !plan.NightMode.Mode.IsNull() && !plan.NightMode.Mode.IsUnknown() {
			v := plan.NightMode.Mode.ValueString()
			cfg.NightMode.Mode = &v
		}
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.RGBCCTSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *rgbcctConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan rgbcctConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *rgbcctConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan rgbcctConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *rgbcctConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *rgbcctConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
