// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &rgbwConfigResource{}
	_ resource.ResourceWithImportState = &rgbwConfigResource{}
)

func NewRGBWConfigResource() resource.Resource { return &rgbwConfigResource{} }

type rgbwConfigResource struct{}

type rgbwConfigNightModeModel struct {
	Enable        types.Bool    `tfsdk:"enable"`
	Brightness    types.Float64 `tfsdk:"brightness"`
	RGB           types.List    `tfsdk:"rgb"`
	White         types.Float64 `tfsdk:"white"`
	ActiveBetween types.List    `tfsdk:"active_between"`
}

type rgbwConfigButtonPresetsButtonDoublepushModel struct {
	Brightness types.Float64 `tfsdk:"brightness"`
	RGB        types.List    `tfsdk:"rgb"`
	White      types.Float64 `tfsdk:"white"`
}

type rgbwConfigButtonPresetsModel struct {
	ButtonDoublepush *rgbwConfigButtonPresetsButtonDoublepushModel `tfsdk:"button_doublepush"`
}

type rgbwConfigResourceModel struct {
	IP                    types.String                  `tfsdk:"ip"`
	ID                    types.Int64                   `tfsdk:"id"`
	Name                  types.String                  `tfsdk:"name"`
	InMode                types.String                  `tfsdk:"in_mode"`
	InitialState          types.String                  `tfsdk:"initial_state"`
	AutoOn                types.Bool                    `tfsdk:"auto_on"`
	AutoOnDelay           types.Float64                 `tfsdk:"auto_on_delay"`
	AutoOff               types.Bool                    `tfsdk:"auto_off"`
	AutoOffDelay          types.Float64                 `tfsdk:"auto_off_delay"`
	TransitionDuration    types.Float64                 `tfsdk:"transition_duration"`
	MinBrightnessOnToggle types.Float64                 `tfsdk:"min_brightness_on_toggle"`
	NightMode             *rgbwConfigNightModeModel     `tfsdk:"night_mode"`
	ButtonFadeRate        types.Float64                 `tfsdk:"button_fade_rate"`
	ButtonPresets         *rgbwConfigButtonPresetsModel `tfsdk:"button_presets"`
	CurrentLimit          types.Float64                 `tfsdk:"current_limit"`
	PowerLimit            types.Float64                 `tfsdk:"power_limit"`
	VoltageLimit          types.Float64                 `tfsdk:"voltage_limit"`
}

func (r *rgbwConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_rgbw_config"
}

func (r *rgbwConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the RGBW component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the RGBW instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"in_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Mode of the associated input. Range of values: follow, flip, activate, detached, dim",
				Validators:          []validator.String{stringvalidator.OneOf("follow", "flip", "activate", "detached", "dim")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"initial_state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Output state to set on power_on. Range of values: off, on, restore_last",
				Validators:          []validator.String{stringvalidator.OneOf("off", "on", "restore_last")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"auto_on": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic ON\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_on_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back on",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"auto_off": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic OFF\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_off_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back off",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"transition_duration": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Transition time (in seconds) - time to change from 0% to 100% of brightness, RGB or white",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"min_brightness_on_toggle": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Brightness level (in percent) applied when there is a toggle and current brightness is lower than min_brightness_on_toggle.",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"night_mode": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Enable or disable night mode",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"brightness": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Brightness level limit (in percent) when night mode is active. null overrides night_mode.brightness with current brightness when night mode starts. Default value 50.",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"rgb": schema.ListAttribute{
						ElementType:         types.Float64Type,
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Color level when night mode is active. Red, Green, Blue [r,g,b] - each value represents level between 0..255. null overrides night_mode.rgb array with current rgb array when night mode starts. Default value 255 for each color",
						PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
					},
					"white": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "White level limit (in percent) when night mode is active. null overrides night_mode.white with current white when night mode starts. Default value 127.",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"active_between": schema.ListAttribute{
						ElementType:         types.StringType,
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Containing 2 elements of type string, the first element indicates the start of the period during which the night mode will be active, the second indicates the end of that period. Both start and end are strings in the format HH:MM, where HH and MM are hours and minutes with optinal leading zeros",
						PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
					},
				},
			},
			"button_fade_rate": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Controls how quickly the output level changes while a button is held down for dimming (if applicable). Default value 3. Range [1,5] where 5 is fastest, 1 is slowest",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"button_presets": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"button_doublepush": schema.SingleNestedAttribute{
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"brightness": schema.Float64Attribute{
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "Brightness level (in percent) set on double click (if applicable). null overrides brightness with current brightness when preset is applied. Default 100",
								PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
							},
							"rgb": schema.ListAttribute{
								ElementType:         types.Float64Type,
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "Color level set on double click (if applicable). Red, Green, Blue [r,g,b] - each value represents level between 0..255. null overrides rgb array with current rgb array when preset is applied. Default value 255 for each color",
								PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
							},
							"white": schema.Float64Attribute{
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "White level 0.255 set on double click (if applicable). null overrides white with current white when preset is applied. Default 255",
								PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
							},
						},
					},
				},
			},
			"current_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Amperes) over which overcurrent condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"power_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Watts) over which overpower condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"voltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Volts) over which overvoltage condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *rgbwConfigResource) get(ctx context.Context, m *rgbwConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.RGBWGetConfigRequest{ID: int(m.ID.ValueInt64())}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		m.Name = types.StringValue(*got.Name)
	}
	if got.InMode != nil {
		m.InMode = types.StringValue(*got.InMode)
	}
	if got.InitialState != nil {
		m.InitialState = types.StringValue(*got.InitialState)
	}
	if got.AutoOn != nil {
		m.AutoOn = types.BoolValue(*got.AutoOn)
	}
	if got.AutoOnDelay != nil {
		m.AutoOnDelay = types.Float64Value(*got.AutoOnDelay)
	}
	if got.AutoOff != nil {
		m.AutoOff = types.BoolValue(*got.AutoOff)
	}
	if got.AutoOffDelay != nil {
		m.AutoOffDelay = types.Float64Value(*got.AutoOffDelay)
	}
	if got.TransitionDuration != nil {
		m.TransitionDuration = types.Float64Value(*got.TransitionDuration)
	}
	if got.MinBrightnessOnToggle != nil {
		m.MinBrightnessOnToggle = types.Float64Value(*got.MinBrightnessOnToggle)
	}
	if got.NightMode != nil {
		if m.NightMode == nil {
			m.NightMode = &rgbwConfigNightModeModel{}
		}
		if got.NightMode.Enable != nil {
			m.NightMode.Enable = types.BoolValue(*got.NightMode.Enable)
		}
		if got.NightMode.Brightness != nil {
			m.NightMode.Brightness = types.Float64Value(*got.NightMode.Brightness)
		}
		if got.NightMode.RGB != nil {
			l, d := types.ListValueFrom(ctx, types.Float64Type, got.NightMode.RGB)
			diags.Append(d...)
			m.NightMode.RGB = l
		}
		if got.NightMode.White != nil {
			m.NightMode.White = types.Float64Value(*got.NightMode.White)
		}
		if got.NightMode.ActiveBetween != nil {
			l, d := types.ListValueFrom(ctx, types.StringType, got.NightMode.ActiveBetween)
			diags.Append(d...)
			m.NightMode.ActiveBetween = l
		}
	}
	if got.ButtonFadeRate != nil {
		m.ButtonFadeRate = types.Float64Value(*got.ButtonFadeRate)
	}
	if got.ButtonPresets != nil {
		if m.ButtonPresets == nil {
			m.ButtonPresets = &rgbwConfigButtonPresetsModel{}
		}
		if got.ButtonPresets.ButtonDoublepush != nil {
			if m.ButtonPresets.ButtonDoublepush == nil {
				m.ButtonPresets.ButtonDoublepush = &rgbwConfigButtonPresetsButtonDoublepushModel{}
			}
			if got.ButtonPresets.ButtonDoublepush.Brightness != nil {
				m.ButtonPresets.ButtonDoublepush.Brightness = types.Float64Value(*got.ButtonPresets.ButtonDoublepush.Brightness)
			}
			if got.ButtonPresets.ButtonDoublepush.RGB != nil {
				l, d := types.ListValueFrom(ctx, types.Float64Type, got.ButtonPresets.ButtonDoublepush.RGB)
				diags.Append(d...)
				m.ButtonPresets.ButtonDoublepush.RGB = l
			}
			if got.ButtonPresets.ButtonDoublepush.White != nil {
				m.ButtonPresets.ButtonDoublepush.White = types.Float64Value(*got.ButtonPresets.ButtonDoublepush.White)
			}
		}
	}
	if got.CurrentLimit != nil {
		m.CurrentLimit = types.Float64Value(*got.CurrentLimit)
	}
	if got.PowerLimit != nil {
		m.PowerLimit = types.Float64Value(*got.PowerLimit)
	}
	if got.VoltageLimit != nil {
		m.VoltageLimit = types.Float64Value(*got.VoltageLimit)
	}
}

func (r *rgbwConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state rgbwConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *rgbwConfigResource) apply(ctx context.Context, plan rgbwConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.RGBWConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.InMode.IsNull() && !plan.InMode.IsUnknown() {
		v := plan.InMode.ValueString()
		cfg.InMode = &v
	}
	if !plan.InitialState.IsNull() && !plan.InitialState.IsUnknown() {
		v := plan.InitialState.ValueString()
		cfg.InitialState = &v
	}
	if !plan.AutoOn.IsNull() && !plan.AutoOn.IsUnknown() {
		v := plan.AutoOn.ValueBool()
		cfg.AutoOn = &v
	}
	if !plan.AutoOnDelay.IsNull() && !plan.AutoOnDelay.IsUnknown() {
		v := plan.AutoOnDelay.ValueFloat64()
		cfg.AutoOnDelay = &v
	}
	if !plan.AutoOff.IsNull() && !plan.AutoOff.IsUnknown() {
		v := plan.AutoOff.ValueBool()
		cfg.AutoOff = &v
	}
	if !plan.AutoOffDelay.IsNull() && !plan.AutoOffDelay.IsUnknown() {
		v := plan.AutoOffDelay.ValueFloat64()
		cfg.AutoOffDelay = &v
	}
	if !plan.TransitionDuration.IsNull() && !plan.TransitionDuration.IsUnknown() {
		v := plan.TransitionDuration.ValueFloat64()
		cfg.TransitionDuration = &v
	}
	if !plan.MinBrightnessOnToggle.IsNull() && !plan.MinBrightnessOnToggle.IsUnknown() {
		v := plan.MinBrightnessOnToggle.ValueFloat64()
		cfg.MinBrightnessOnToggle = &v
	}
	if plan.NightMode != nil {
		cfg.NightMode = &components.RGBWConfigNightMode{}
		if !plan.NightMode.Enable.IsNull() && !plan.NightMode.Enable.IsUnknown() {
			v := plan.NightMode.Enable.ValueBool()
			cfg.NightMode.Enable = &v
		}
		if !plan.NightMode.Brightness.IsNull() && !plan.NightMode.Brightness.IsUnknown() {
			v := plan.NightMode.Brightness.ValueFloat64()
			cfg.NightMode.Brightness = &v
		}
		if !plan.NightMode.RGB.IsNull() && !plan.NightMode.RGB.IsUnknown() {
			var v []float64
			diags.Append(plan.NightMode.RGB.ElementsAs(ctx, &v, false)...)
			cfg.NightMode.RGB = v
		}
		if !plan.NightMode.White.IsNull() && !plan.NightMode.White.IsUnknown() {
			v := plan.NightMode.White.ValueFloat64()
			cfg.NightMode.White = &v
		}
		if !plan.NightMode.ActiveBetween.IsNull() && !plan.NightMode.ActiveBetween.IsUnknown() {
			var v []string
			diags.Append(plan.NightMode.ActiveBetween.ElementsAs(ctx, &v, false)...)
			cfg.NightMode.ActiveBetween = v
		}
	}
	if !plan.ButtonFadeRate.IsNull() && !plan.ButtonFadeRate.IsUnknown() {
		v := plan.ButtonFadeRate.ValueFloat64()
		cfg.ButtonFadeRate = &v
	}
	if plan.ButtonPresets != nil {
		cfg.ButtonPresets = &components.RGBWConfigButtonPresets{}
		if plan.ButtonPresets.ButtonDoublepush != nil {
			cfg.ButtonPresets.ButtonDoublepush = &components.RGBWConfigButtonPresetsButtonDoublepush{}
			if !plan.ButtonPresets.ButtonDoublepush.Brightness.IsNull() && !plan.ButtonPresets.ButtonDoublepush.Brightness.IsUnknown() {
				v := plan.ButtonPresets.ButtonDoublepush.Brightness.ValueFloat64()
				cfg.ButtonPresets.ButtonDoublepush.Brightness = &v
			}
			if !plan.ButtonPresets.ButtonDoublepush.RGB.IsNull() && !plan.ButtonPresets.ButtonDoublepush.RGB.IsUnknown() {
				var v []float64
				diags.Append(plan.ButtonPresets.ButtonDoublepush.RGB.ElementsAs(ctx, &v, false)...)
				cfg.ButtonPresets.ButtonDoublepush.RGB = v
			}
			if !plan.ButtonPresets.ButtonDoublepush.White.IsNull() && !plan.ButtonPresets.ButtonDoublepush.White.IsUnknown() {
				v := plan.ButtonPresets.ButtonDoublepush.White.ValueFloat64()
				cfg.ButtonPresets.ButtonDoublepush.White = &v
			}
		}
	}
	if !plan.CurrentLimit.IsNull() && !plan.CurrentLimit.IsUnknown() {
		v := plan.CurrentLimit.ValueFloat64()
		cfg.CurrentLimit = &v
	}
	if !plan.PowerLimit.IsNull() && !plan.PowerLimit.IsUnknown() {
		v := plan.PowerLimit.ValueFloat64()
		cfg.PowerLimit = &v
	}
	if !plan.VoltageLimit.IsNull() && !plan.VoltageLimit.IsUnknown() {
		v := plan.VoltageLimit.ValueFloat64()
		cfg.VoltageLimit = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.RGBWSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *rgbwConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan rgbwConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *rgbwConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan rgbwConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *rgbwConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *rgbwConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
