// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &switchConfigResource{}
	_ resource.ResourceWithImportState = &switchConfigResource{}
)

func NewSwitchConfigResource() resource.Resource { return &switchConfigResource{} }

type switchConfigResource struct{}

type switchConfigCountsModel struct {
	Enable   types.Bool    `tfsdk:"enable"`
	PowerThr types.Float64 `tfsdk:"power_thr"`
}

type switchConfigResourceModel struct {
	IP                       types.String             `tfsdk:"ip"`
	ID                       types.Int64              `tfsdk:"id"`
	Name                     types.String             `tfsdk:"name"`
	InMode                   types.String             `tfsdk:"in_mode"`
	InLocked                 types.Bool               `tfsdk:"in_locked"`
	InitialState             types.String             `tfsdk:"initial_state"`
	AutoOn                   types.Bool               `tfsdk:"auto_on"`
	AutoOnDelay              types.Float64            `tfsdk:"auto_on_delay"`
	AutoOff                  types.Bool               `tfsdk:"auto_off"`
	AutoOffDelay             types.Float64            `tfsdk:"auto_off_delay"`
	AutorecoverVoltageErrors types.Bool               `tfsdk:"autorecover_voltage_errors"`
	InputID                  types.Float64            `tfsdk:"input_id"`
	PowerLimit               types.Float64            `tfsdk:"power_limit"`
	VoltageLimit             types.Float64            `tfsdk:"voltage_limit"`
	UndervoltageLimit        types.Float64            `tfsdk:"undervoltage_limit"`
	CurrentLimit             types.Float64            `tfsdk:"current_limit"`
	Reverse                  types.Bool               `tfsdk:"reverse"`
	Counts                   *switchConfigCountsModel `tfsdk:"counts"`
}

func (r *switchConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_switch_config"
}

func (r *switchConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the Switch component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the switch instance",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"in_mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Mode of the associated input. Range of values: momentary, follow, flip, detached, cycle (if applicable), activate (if applicable)",
				Validators:          []validator.String{stringvalidator.OneOf("momentary", "follow", "flip", "detached", "cycle")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"in_locked": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "If True, all changes to physical inputs are ignored, regardless of mode.",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"initial_state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Output state to set on power_on. Range of values: off, on, restore_last, match_input",
				Validators:          []validator.String{stringvalidator.OneOf("off", "on", "restore_last", "match_input")},
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"auto_on": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic ON\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_on_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back on",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"auto_off": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if the \"Automatic OFF\" function is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"auto_off_delay": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Seconds to pass until the component is switched back off",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"autorecover_voltage_errors": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "True if switch output state should be restored after over/undervoltage error is cleared, false otherwise (shown if applicable)",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"input_id": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Id of the Input component which controls the Switch. Applicable only to Pro1, Pro1PM and 1LG3 devices. Valid values: 0, 1",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"power_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Watts) over which overpower condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"voltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Volts) over which overvoltage condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"undervoltage_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Limit (in Volts) under which undervoltage condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"current_limit": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Number, limit (in Amperes) over which overcurrent condition occurs (shown if applicable)",
				PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
			},
			"reverse": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Reverse measurement direction of active power and energy. setting the reverse option requires restart (shown if applicable)",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"counts": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Enable or disable the switch counters (shown if applicable)",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"power_thr": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Active power threshold (in Watts) over which on_above_thr counter is incremented. Default value 100. (shown if applicable)",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
		},
	}
}

func (r *switchConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state switchConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&components.SwitchGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		state.Name = types.StringValue(*got.Name)
	}
	if got.InMode != nil {
		state.InMode = types.StringValue(*got.InMode)
	}
	if got.InLocked != nil {
		state.InLocked = types.BoolValue(*got.InLocked)
	}
	if got.InitialState != nil {
		state.InitialState = types.StringValue(*got.InitialState)
	}
	if got.AutoOn != nil {
		state.AutoOn = types.BoolValue(*got.AutoOn)
	}
	if got.AutoOnDelay != nil {
		state.AutoOnDelay = types.Float64Value(*got.AutoOnDelay)
	}
	if got.AutoOff != nil {
		state.AutoOff = types.BoolValue(*got.AutoOff)
	}
	if got.AutoOffDelay != nil {
		state.AutoOffDelay = types.Float64Value(*got.AutoOffDelay)
	}
	if got.AutorecoverVoltageErrors != nil {
		state.AutorecoverVoltageErrors = types.BoolValue(*got.AutorecoverVoltageErrors)
	}
	if got.InputID != nil {
		state.InputID = types.Float64Value(*got.InputID)
	}
	if got.PowerLimit != nil {
		state.PowerLimit = types.Float64Value(*got.PowerLimit)
	}
	if got.VoltageLimit != nil {
		state.VoltageLimit = types.Float64Value(*got.VoltageLimit)
	}
	if got.UndervoltageLimit != nil {
		state.UndervoltageLimit = types.Float64Value(*got.UndervoltageLimit)
	}
	if got.CurrentLimit != nil {
		state.CurrentLimit = types.Float64Value(*got.CurrentLimit)
	}
	if got.Reverse != nil {
		state.Reverse = types.BoolValue(*got.Reverse)
	}
	if got.Counts != nil {
		if state.Counts == nil {
			state.Counts = &switchConfigCountsModel{}
		}
		if got.Counts.Enable != nil {
			state.Counts.Enable = types.BoolValue(*got.Counts.Enable)
		}
		if got.Counts.PowerThr != nil {
			state.Counts.PowerThr = types.Float64Value(*got.Counts.PowerThr)
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *switchConfigResource) apply(plan switchConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.SwitchConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	if !plan.InMode.IsNull() && !plan.InMode.IsUnknown() {
		v := plan.InMode.ValueString()
		cfg.InMode = &v
	}
	if !plan.InLocked.IsNull() && !plan.InLocked.IsUnknown() {
		v := plan.InLocked.ValueBool()
		cfg.InLocked = &v
	}
	if !plan.InitialState.IsNull() && !plan.InitialState.IsUnknown() {
		v := plan.InitialState.ValueString()
		cfg.InitialState = &v
	}
	if !plan.AutoOn.IsNull() && !plan.AutoOn.IsUnknown() {
		v := plan.AutoOn.ValueBool()
		cfg.AutoOn = &v
	}
	if !plan.AutoOnDelay.IsNull() && !plan.AutoOnDelay.IsUnknown() {
		v := plan.AutoOnDelay.ValueFloat64()
		cfg.AutoOnDelay = &v
	}
	if !plan.AutoOff.IsNull() && !plan.AutoOff.IsUnknown() {
		v := plan.AutoOff.ValueBool()
		cfg.AutoOff = &v
	}
	if !plan.AutoOffDelay.IsNull() && !plan.AutoOffDelay.IsUnknown() {
		v := plan.AutoOffDelay.ValueFloat64()
		cfg.AutoOffDelay = &v
	}
	if !plan.AutorecoverVoltageErrors.IsNull() && !plan.AutorecoverVoltageErrors.IsUnknown() {
		v := plan.AutorecoverVoltageErrors.ValueBool()
		cfg.AutorecoverVoltageErrors = &v
	}
	if !plan.InputID.IsNull() && !plan.InputID.IsUnknown() {
		v := plan.InputID.ValueFloat64()
		cfg.InputID = &v
	}
	if !plan.PowerLimit.IsNull() && !plan.PowerLimit.IsUnknown() {
		v := plan.PowerLimit.ValueFloat64()
		cfg.PowerLimit = &v
	}
	if !plan.VoltageLimit.IsNull() && !plan.VoltageLimit.IsUnknown() {
		v := plan.VoltageLimit.ValueFloat64()
		cfg.VoltageLimit = &v
	}
	if !plan.UndervoltageLimit.IsNull() && !plan.UndervoltageLimit.IsUnknown() {
		v := plan.UndervoltageLimit.ValueFloat64()
		cfg.UndervoltageLimit = &v
	}
	if !plan.CurrentLimit.IsNull() && !plan.CurrentLimit.IsUnknown() {
		v := plan.CurrentLimit.ValueFloat64()
		cfg.CurrentLimit = &v
	}
	if !plan.Reverse.IsNull() && !plan.Reverse.IsUnknown() {
		v := plan.Reverse.ValueBool()
		cfg.Reverse = &v
	}
	if plan.Counts != nil {
		cfg.Counts = &components.SwitchConfigCounts{}
		if !plan.Counts.Enable.IsNull() && !plan.Counts.Enable.IsUnknown() {
			v := plan.Counts.Enable.ValueBool()
			cfg.Counts.Enable = &v
		}
		if !plan.Counts.PowerThr.IsNull() && !plan.Counts.PowerThr.IsUnknown() {
			v := plan.Counts.PowerThr.ValueFloat64()
			cfg.Counts.PowerThr = &v
		}
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.SwitchSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *switchConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan switchConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *switchConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan switchConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *switchConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *switchConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
