// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/DonRobo/shelly-go"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
	"strconv"
	"strings"
)

var (
	_ resource.Resource                = &temperatureConfigResource{}
	_ resource.ResourceWithImportState = &temperatureConfigResource{}
)

func NewTemperatureConfigResource() resource.Resource { return &temperatureConfigResource{} }

type temperatureConfigResource struct{}

type temperatureConfigResourceModel struct {
	IP   types.String `tfsdk:"ip"`
	ID   types.Int64  `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}

func (r *temperatureConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_temperature_config"
}

func (r *temperatureConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"id": schema.Int64Attribute{Required: true, MarkdownDescription: "The ID of the Temperature component instance."},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the Temperature instance. name length should not exceed 64 chars",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *temperatureConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state temperatureConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&shelly.TemperatureGetConfigRequest{ID: int(state.ID.ValueInt64())}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.Name != nil {
		state.Name = types.StringValue(*got.Name)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *temperatureConfigResource) apply(plan temperatureConfigResourceModel, diags *diag.Diagnostics) {
	var cfg shelly.TemperatureConfig
	cfg.ID = int(plan.ID.ValueInt64())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		v := plan.Name.ValueString()
		cfg.Name = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&shelly.TemperatureSetConfigRequest{ID: int(plan.ID.ValueInt64()), Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *temperatureConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan temperatureConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *temperatureConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan temperatureConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *temperatureConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *temperatureConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.Split(req.ID, ":")
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid import ID", "Expected format ip:id")
		return
	}
	id, err := strconv.Atoi(parts[1])
	if err != nil {
		resp.Diagnostics.AddError("Invalid import ID", fmt.Sprintf("id must be an integer: %v", err))
		return
	}
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("ip"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
