// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &wifiConfigResource{}
	_ resource.ResourceWithImportState = &wifiConfigResource{}
)

func NewWifiConfigResource() resource.Resource { return &wifiConfigResource{} }

type wifiConfigResource struct{}

type wifiConfigAPRangeExtenderModel struct {
	Enable types.Bool `tfsdk:"enable"`
}

type wifiConfigAPModel struct {
	SSID          types.String                    `tfsdk:"ssid"`
	Pass          types.String                    `tfsdk:"pass"`
	IsOpen        types.Bool                      `tfsdk:"is_open"`
	Enable        types.Bool                      `tfsdk:"enable"`
	RangeExtender *wifiConfigAPRangeExtenderModel `tfsdk:"range_extender"`
}

type wifiConfigStaModel struct {
	SSID       types.String `tfsdk:"ssid"`
	Pass       types.String `tfsdk:"pass"`
	IsOpen     types.Bool   `tfsdk:"is_open"`
	Enable     types.Bool   `tfsdk:"enable"`
	Ipv4mode   types.String `tfsdk:"ipv4mode"`
	IP         types.String `tfsdk:"ip"`
	Netmask    types.String `tfsdk:"netmask"`
	Gw         types.String `tfsdk:"gw"`
	Nameserver types.String `tfsdk:"nameserver"`
}

type wifiConfigRoamModel struct {
	RssiThr  types.Float64 `tfsdk:"rssi_thr"`
	Interval types.Float64 `tfsdk:"interval"`
}

type wifiConfigResourceModel struct {
	IP   types.String         `tfsdk:"ip"`
	AP   *wifiConfigAPModel   `tfsdk:"ap"`
	Sta  *wifiConfigStaModel  `tfsdk:"sta"`
	Roam *wifiConfigRoamModel `tfsdk:"roam"`
}

func (r *wifiConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_wifi_config"
}

func (r *wifiConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"ap": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"ssid": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "SSID of the access point (up to 29 symbols). Default is the deviceID, set to null to restore default. optional",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"pass": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Password for the AP network, writeonly. Default is open network, set to null to restore default. optional",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"is_open": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "True if the access point is open, false otherwise",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "True if the access point is enabled, false otherwise",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"range_extender": schema.SingleNestedAttribute{
						Optional:      true,
						Computed:      true,
						PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
						Attributes: map[string]schema.Attribute{
							"enable": schema.BoolAttribute{
								Optional:            true,
								Computed:            true,
								MarkdownDescription: "True if range extender functionality is enabled, false otherwise",
								PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
							},
						},
					},
				},
			},
			"sta": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"ssid": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "SSID of the network.",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"pass": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Password for the SSID, writeonly. Must be provided if you provide ssid",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"is_open": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "True if the network is open, i.e. no password is set, false otherwise, readonly",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"enable": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "True if the configuration is enabled, false otherwise",
						PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
					},
					"ipv4mode": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "IPv4 mode. Range of values: dhcp, static",
						Validators:          []validator.String{stringvalidator.OneOf("dhcp", "static")},
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"ip": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Ip to use when ipv4mode is static",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"netmask": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Netmask to use when ipv4mode is static",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"gw": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Gateway to use when ipv4mode is static",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
					"nameserver": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Nameserver to use when ipv4mode is static",
						PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
					},
				},
			},
			"roam": schema.SingleNestedAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
				Attributes: map[string]schema.Attribute{
					"rssi_thr": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Rssi threshold - when reached will trigger the access point roaming. Default value: -80",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
					"interval": schema.Float64Attribute{
						Optional:            true,
						Computed:            true,
						MarkdownDescription: "Interval at which to scan for better access points. Enabled if set to positive number, disabled if set to 0. Default value: 60",
						PlanModifiers:       []planmodifier.Float64{float64planmodifier.UseStateForUnknown()},
					},
				},
			},
		},
	}
}

func (r *wifiConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state wifiConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + state.IP.ValueString())
	got, _, err := (&components.WifiGetConfigRequest{}).Do(client)
	if err != nil {
		resp.Diagnostics.AddError("Failed to read config", err.Error())
		return
	}
	if got.AP != nil {
		if state.AP == nil {
			state.AP = &wifiConfigAPModel{}
		}
		if got.AP.SSID != nil {
			state.AP.SSID = types.StringValue(*got.AP.SSID)
		}
		if got.AP.Pass != nil {
			state.AP.Pass = types.StringValue(*got.AP.Pass)
		}
		if got.AP.IsOpen != nil {
			state.AP.IsOpen = types.BoolValue(*got.AP.IsOpen)
		}
		if got.AP.Enable != nil {
			state.AP.Enable = types.BoolValue(*got.AP.Enable)
		}
		if got.AP.RangeExtender != nil {
			if state.AP.RangeExtender == nil {
				state.AP.RangeExtender = &wifiConfigAPRangeExtenderModel{}
			}
			if got.AP.RangeExtender.Enable != nil {
				state.AP.RangeExtender.Enable = types.BoolValue(*got.AP.RangeExtender.Enable)
			}
		}
	}
	if got.Sta != nil {
		if state.Sta == nil {
			state.Sta = &wifiConfigStaModel{}
		}
		if got.Sta.SSID != nil {
			state.Sta.SSID = types.StringValue(*got.Sta.SSID)
		}
		if got.Sta.Pass != nil {
			state.Sta.Pass = types.StringValue(*got.Sta.Pass)
		}
		if got.Sta.IsOpen != nil {
			state.Sta.IsOpen = types.BoolValue(*got.Sta.IsOpen)
		}
		if got.Sta.Enable != nil {
			state.Sta.Enable = types.BoolValue(*got.Sta.Enable)
		}
		if got.Sta.Ipv4mode != nil {
			state.Sta.Ipv4mode = types.StringValue(*got.Sta.Ipv4mode)
		}
		if got.Sta.IP != nil {
			state.Sta.IP = types.StringValue(*got.Sta.IP)
		}
		if got.Sta.Netmask != nil {
			state.Sta.Netmask = types.StringValue(*got.Sta.Netmask)
		}
		if got.Sta.Gw != nil {
			state.Sta.Gw = types.StringValue(*got.Sta.Gw)
		}
		if got.Sta.Nameserver != nil {
			state.Sta.Nameserver = types.StringValue(*got.Sta.Nameserver)
		}
	}
	if got.Roam != nil {
		if state.Roam == nil {
			state.Roam = &wifiConfigRoamModel{}
		}
		if got.Roam.RssiThr != nil {
			state.Roam.RssiThr = types.Float64Value(*got.Roam.RssiThr)
		}
		if got.Roam.Interval != nil {
			state.Roam.Interval = types.Float64Value(*got.Roam.Interval)
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *wifiConfigResource) apply(plan wifiConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.WifiConfig
	if plan.AP != nil {
		cfg.AP = &components.WifiConfigAP{}
		if !plan.AP.SSID.IsNull() && !plan.AP.SSID.IsUnknown() {
			v := plan.AP.SSID.ValueString()
			cfg.AP.SSID = &v
		}
		if !plan.AP.Pass.IsNull() && !plan.AP.Pass.IsUnknown() {
			v := plan.AP.Pass.ValueString()
			cfg.AP.Pass = &v
		}
		if !plan.AP.IsOpen.IsNull() && !plan.AP.IsOpen.IsUnknown() {
			v := plan.AP.IsOpen.ValueBool()
			cfg.AP.IsOpen = &v
		}
		if !plan.AP.Enable.IsNull() && !plan.AP.Enable.IsUnknown() {
			v := plan.AP.Enable.ValueBool()
			cfg.AP.Enable = &v
		}
		if plan.AP.RangeExtender != nil {
			cfg.AP.RangeExtender = &components.WifiConfigAPRangeExtender{}
			if !plan.AP.RangeExtender.Enable.IsNull() && !plan.AP.RangeExtender.Enable.IsUnknown() {
				v := plan.AP.RangeExtender.Enable.ValueBool()
				cfg.AP.RangeExtender.Enable = &v
			}
		}
	}
	if plan.Sta != nil {
		cfg.Sta = &components.WifiConfigSta{}
		if !plan.Sta.SSID.IsNull() && !plan.Sta.SSID.IsUnknown() {
			v := plan.Sta.SSID.ValueString()
			cfg.Sta.SSID = &v
		}
		if !plan.Sta.Pass.IsNull() && !plan.Sta.Pass.IsUnknown() {
			v := plan.Sta.Pass.ValueString()
			cfg.Sta.Pass = &v
		}
		if !plan.Sta.IsOpen.IsNull() && !plan.Sta.IsOpen.IsUnknown() {
			v := plan.Sta.IsOpen.ValueBool()
			cfg.Sta.IsOpen = &v
		}
		if !plan.Sta.Enable.IsNull() && !plan.Sta.Enable.IsUnknown() {
			v := plan.Sta.Enable.ValueBool()
			cfg.Sta.Enable = &v
		}
		if !plan.Sta.Ipv4mode.IsNull() && !plan.Sta.Ipv4mode.IsUnknown() {
			v := plan.Sta.Ipv4mode.ValueString()
			cfg.Sta.Ipv4mode = &v
		}
		if !plan.Sta.IP.IsNull() && !plan.Sta.IP.IsUnknown() {
			v := plan.Sta.IP.ValueString()
			cfg.Sta.IP = &v
		}
		if !plan.Sta.Netmask.IsNull() && !plan.Sta.Netmask.IsUnknown() {
			v := plan.Sta.Netmask.ValueString()
			cfg.Sta.Netmask = &v
		}
		if !plan.Sta.Gw.IsNull() && !plan.Sta.Gw.IsUnknown() {
			v := plan.Sta.Gw.ValueString()
			cfg.Sta.Gw = &v
		}
		if !plan.Sta.Nameserver.IsNull() && !plan.Sta.Nameserver.IsUnknown() {
			v := plan.Sta.Nameserver.ValueString()
			cfg.Sta.Nameserver = &v
		}
	}
	if plan.Roam != nil {
		cfg.Roam = &components.WifiConfigRoam{}
		if !plan.Roam.RssiThr.IsNull() && !plan.Roam.RssiThr.IsUnknown() {
			v := plan.Roam.RssiThr.ValueFloat64()
			cfg.Roam.RssiThr = &v
		}
		if !plan.Roam.Interval.IsNull() && !plan.Roam.Interval.IsUnknown() {
			v := plan.Roam.Interval.ValueFloat64()
			cfg.Roam.Interval = &v
		}
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.WifiSetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *wifiConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan wifiConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wifiConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan wifiConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wifiConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *wifiConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
