// Code generated by internal/provider/gen from the Shelly API docs. DO NOT EDIT.

package provider

import (
	"context"
	"github.com/DonRobo/shelly-go/components"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"resty.dev/v3"
)

var (
	_ resource.Resource                = &wsConfigResource{}
	_ resource.ResourceWithImportState = &wsConfigResource{}
)

func NewWsConfigResource() resource.Resource { return &wsConfigResource{} }

type wsConfigResource struct{}

type wsConfigResourceModel struct {
	IP     types.String `tfsdk:"ip"`
	Enable types.Bool   `tfsdk:"enable"`
	Server types.String `tfsdk:"server"`
}

func (r *wsConfigResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ws_config"
}

func (r *wsConfigResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"ip": schema.StringAttribute{Required: true, MarkdownDescription: "The IP address of the Shelly device."},
			"enable": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "true if websocket outbound connection is enabled, false otherwise",
				PlanModifiers:       []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
			},
			"server": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "Name of the server to which the device is connected. When prefixed with wss:// a TLS socket will be used",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *wsConfigResource) get(ctx context.Context, m *wsConfigResourceModel, diags *diag.Diagnostics) {
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + m.IP.ValueString())
	got, _, err := (&components.WsGetConfigRequest{}).Do(client)
	if err != nil {
		diags.AddError("Failed to read config", err.Error())
		return
	}
	if got.Enable != nil {
		m.Enable = types.BoolValue(*got.Enable)
	}
	if got.Server != nil {
		m.Server = types.StringValue(*got.Server)
	}
}

func (r *wsConfigResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state wsConfigResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &state, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *wsConfigResource) apply(ctx context.Context, plan wsConfigResourceModel, diags *diag.Diagnostics) {
	var cfg components.WsConfig
	if !plan.Enable.IsNull() && !plan.Enable.IsUnknown() {
		v := plan.Enable.ValueBool()
		cfg.Enable = &v
	}
	if !plan.Server.IsNull() && !plan.Server.IsUnknown() {
		v := plan.Server.ValueString()
		cfg.Server = &v
	}
	client := resty.New()
	defer client.Close()
	client.SetBaseURL("http://" + plan.IP.ValueString())
	if _, _, err := (&components.WsSetConfigRequest{Config: cfg}).Do(client); err != nil {
		diags.AddError("Failed to set config", err.Error())
	}
}

func (r *wsConfigResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan wsConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wsConfigResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan wsConfigResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	r.apply(ctx, plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	r.get(ctx, &plan, &resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *wsConfigResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.State.RemoveResource(ctx)
}

func (r *wsConfigResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("ip"), req, resp)
}
